### ISSUE TITLE
Issue External ElasticSearch on Windows Installation

### ISSUE THREAD

**Issue by mon-routeur** [codelibs/fess#1187]
Hello, i try to configure an external Elasticsearch (5.4.1) Installed and Running on Windows with Fess.
I follow this step : http://fess.codelibs.org/11.2/install/install.html#using-your-elasticsearch-cluster-on-zip-package
I removed rem from the last 3 lines of fess.in.bat file
```
REM External elasticsearch cluster
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.es.http_address=http://localhost:9200
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.es.transport_addresses=localhost:9300
set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.dictionary.path="C:\elasticsearch\config" 
```
But i have a error message when Fess start.

```
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:9200/_configsync/wait?status=green
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at org.codelibs.elasticsearch.runner.net.CurlRequest$1$1.open(CurlRequest.java:178)
	at org.codelibs.elasticsearch.runner.net.CurlRequest$1.writeContent(CurlRequest.java:208)
	at org.codelibs.elasticsearch.runner.net.CurlRequest$1.onResponse(CurlRequest.java:175)
	at org.codelibs.elasticsearch.runner.net.CurlRequest.execute(CurlRequest.java:157)
	at org.codelibs.elasticsearch.runner.net.CurlRequest.execute(CurlRequest.java:169)
	at org.codelibs.fess.es.client.FessEsClient.waitForConfigSyncStatus(FessEsClient.java:597)
	... 40 more
```
Thank you in advance for your answer.

**Comment by marevol** [comment]
Could you check elasticsearch log file?
network.host setting might be needed.

**Comment by mon-routeur** [comment]
Thank you for your answer.
Please find the elasticsearch log file```

[2017-07-26T11:50:03,006][WARN ][o.e.t.n.Netty4Transport  ] [oJ2Y5c3] exception caught on transport layer [[id: 0xf5c00ea4, L:/127.0.0.1:9300 - R:/127.0.0.1:49535]], closing connection
java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:?]
	at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

**Comment by marevol** [comment]
Fess seemed to disconnect access to elasticsearch.
Are there other exceptions in fess.log?

**Comment by jstaerk** [comment]
I just had the same issue, I had replaced and accidentally removed the  trailing / of the fess.dictionary.path in my fess.in.bat 
`set FESS_JAVA_OPTS=%FESS_JAVA_OPTS% -Dfess.dictionary.path=/ProgramData/Elastic/Elasticsearch/config`.

Accordingly the fess.log told me 

```
2017-08-30 12:58:34,114 [localhost-startStop-1] WARN  fess_indices/fess.json is not found.
java.lang.SecurityException: access denied ("java.io.FilePermission" "C:\ProgramData\Elastic\Elasticsearch\configja\mapping.txt" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_131]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_131]

```
of course there is no configja but a config\ja on my system.
It's not clear why the mapping seems to be defined for the japanese locale (would rather be german=de in my case) but thanks for this thread (which pointed me to fess.log) and thanks for the great software.

**Comment by marevol** [comment]
Fess is i18ned/l10ned software.
So, over 30 language supports are defined in the mapping.
