### ISSUE TITLE
NPE on SuggestIndexer

### ISSUE THREAD

**Issue by marevol** [codelibs/fess#1203]
```
2017-08-02 22:49:01,095 [job_log_aggregator] ERROR Failed to store a search log.
org.codelibs.fess.suggest.exception.SuggestIndexException: Failed to index from document
	at org.codelibs.fess.suggest.index.SuggestIndexer.indexFromSearchWord(SuggestIndexer.java:343) ~[fess-suggest-5.5.0-SNAPSHOT.jar:?]
	at org.codelibs.fess.helper.SuggestHelper.lambda$indexFromSearchLog$1592(SuggestHelper.java:174) ~[classes/:?]
	at org.codelibs.fess.helper.SuggestHelper$$Lambda$1457/550408993.accept(Unknown Source) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_45]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_45]
	at org.codelibs.fess.helper.SuggestHelper.indexFromSearchLog(SuggestHelper.java:133) ~[classes/:?]
	at org.codelibs.fess.helper.SearchLogHelper.processSearchLogQueue(SearchLogHelper.java:259) ~[classes/:?]
	at org.codelibs.fess.helper.SearchLogHelper.storeSearchLog(SearchLogHelper.java:152) ~[classes/:?]
	at org.codelibs.fess.job.AggregateLogJob.execute(AggregateLogJob.java:33) [classes/:?]
	at org.codelibs.fess.job.AggregateLogJob$execute.call(Unknown Source) [classes/:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.11.jar:2.4.11]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.11.jar:2.4.11]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-all-2.4.11.jar:2.4.11]
	at Script1.run(Script1.groovy:1) [shell:?]
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585) [groovy-all-2.4.11.jar:2.4.11]
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623) [groovy-all-2.4.11.jar:2.4.11]
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594) [groovy-all-2.4.11.jar:2.4.11]
	at org.codelibs.fess.util.GroovyUtil.evaluate(GroovyUtil.java:41) [classes/:?]
	at org.codelibs.fess.job.impl.GroovyExecutor.execute(GroovyExecutor.java:31) [classes/:?]
	at org.codelibs.fess.app.job.ScriptExecutorJob.run(ScriptExecutorJob.java:92) [classes/:?]
	at org.lastaflute.job.LaJobRunner.actuallyRun(LaJobRunner.java:262) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.LaJobRunner.doRun(LaJobRunner.java:229) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.LaJobRunner.run(LaJobRunner.java:179) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.runJob(Cron4jTask.java:371) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.actuallyExecute(Cron4jTask.java:355) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.lambda$doExecute$6(Cron4jTask.java:258) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask$$Lambda$1372/708343360.get(Unknown Source) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.synchronizedNeighborRunning(Cron4jTask.java:328) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.doExecute(Cron4jTask.java:246) [lasta-job-0.5.0.jar:?]
	at org.lastaflute.job.cron4j.Cron4jTask.execute(Cron4jTask.java:151) [lasta-job-0.5.0.jar:?]
	at it.sauronsoftware.cron4j.RomanticCron4jNativeTaskExecutor$RomanticRunner.run(RomanticCron4jNativeTaskExecutor.java:121) [lasta-job-0.5.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
	at java.lang.String.contains(String.java:2121) ~[?:1.8.0_45]
	at org.codelibs.fess.suggest.entity.SuggestItem.isNgWord(SuggestItem.java:495) ~[fess-suggest-5.5.0-SNAPSHOT.jar:?]
	at org.codelibs.fess.suggest.index.SuggestIndexer.lambda$index$21(SuggestIndexer.java:97) ~[fess-suggest-5.5.0-SNAPSHOT.jar:?]
	at org.codelibs.fess.suggest.index.SuggestIndexer$$Lambda$1467/905858982.test(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_45]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_45]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_45]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_45]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:576) ~[?:1.8.0_45]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:255) ~[?:1.8.0_45]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_45]
	at org.codelibs.fess.suggest.index.SuggestIndexer.index(SuggestIndexer.java:97) ~[fess-suggest-5.5.0-SNAPSHOT.jar:?]
	at org.codelibs.fess.suggest.index.SuggestIndexer.index(SuggestIndexer.java:91) ~[fess-suggest-5.5.0-SNAPSHOT.jar:?]
	at org.codelibs.fess.suggest.index.SuggestIndexer.indexFromSearchWord(SuggestIndexer.java:340) ~[fess-suggest-5.5.0-SNAPSHOT.jar:?]
	... 31 more
```

**Comment by marevol** [comment]
fixed in https://github.com/codelibs/fess-suggest/commit/199266b7224f0f54422c1747ae1833683c8ebdf0
