### ISSUE TITLE
fails to boot with external elastic cluster

### ISSUE THREAD

**Issue by eimperat** [codelibs/fess#1227]
elastic 5.3.1, fess 11.2 unpacked from .tar.gz file
I'm able to run ./fess on its own, by not specifying 
ES_HTTP_URL/ES_TRANSPORT_URL/FESS_DICTIONARY_PATH in fess.in.sh
but when those are given values, and it tries to connect with the existing running elastic cluster at localhost:9200, i get the following error:

 [localhost-startStop-1] WARN  fess_indices/fess.json is not found.
java.lang.IllegalArgumentException: Unknown char_filter type [fess_traditional_chinese_convert] for [traditional_chinese_convert]
        at org.elasticsearch.index.analysis.AnalysisRegistry.getAnalysisProvider(AnalysisRegistry.java:387) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:338) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildCharFilterFactories(AnalysisRegistry.java:181) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:153) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.index.IndexService.<init>(IndexService.java:145) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:363) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:427) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:392) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:364) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:679) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:658) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:617) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:1117) ~[?:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:544) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) ~[elasticsearch-5.4.2.jar:5.4.2]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) ~[elasticsearch-5.4.2.jar:5.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

then the server log file says
Aug 14, 2017 12:10:27 PM org.dbflute.tomcat.logging.BootLogger info
INFO: Boot successful: url -> http://localhost:8080
but curl to port shows 404

thanks, i've been stuck trying to debug this for a while now

**Comment by marevol** [comment]
For Fess 11.2, you need to install analysis-fess 5.4.2(See [Installation](http://fess.codelibs.org/11.2/install/install.html#using-rpm-package)).
I do not think it supports Elasticsearch 5.3. So, Elasticsearch need to be upgraded to 5.4.

**Comment by eimperat** [comment]
i've moved to the newest installation instructions, for fess 11.3 and elastic 5.5, with all the plugins updated as per the instructions, but now see the following;
 WARN  Invalid request for ar/protwords.txt.
java.io.IOException: Server returned HTTP response code: 503 for URL: http://localhost:9200/_configsync/file?path=ar%2Fprotwords.txt

**Comment by eimperat** [comment]
i moved to fess 1.13, and elastic 5.5.1,installed the 5.5.0 version plugins and the system is now working perfectly :)
great software, keep up the good work!
