### ISSUE TITLE
Can't start fess in docker (ver 11, 11.2, 11.2.2)

### ISSUE THREAD

**Issue by boyoyon8** [codelibs/fess#1249]
I can't start fess in docker due to elasticsearch `java.net.UnknownHostException` error.

command
```
docker run -d -p 8080:8080 --name fess codelibs/fess:latest
```

/var/log/elasticsearch/elasticsearch.log(in docker container)
```
java.net.UnknownHostException: elasticsearch: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_141]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_141]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_141]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_141]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_141]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_141]
	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:922) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:877) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:674) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$null$0(UnicastZenPing.java:213) ~[elasticsearch-5.4.2.jar:5.4.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_141]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.4.2.jar:5.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

/var/log/fess/fess.log(in docker container)
```
2017-08-29 01:52:37,060 [localhost-startStop-1] WARN  Failed to create fess.20170829/doc mapping.
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes were available: [{2v50b_I}{2v50b_I5Qm64127dhwhwuw}{Fcu6dx8kSGWr4rU-n_dWbA}{172.17.0.2}{127.0.0.1:9300}]
	at org.elasticsearch.client.transport.TransportClientNodesService$RetryListener.onFailure(TransportClientNodesService.java:292) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1050) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.transport.TransportService$Adapter.lambda$onConnectionClosed$6(TransportService.java:876) ~[elasticsearch-5.4.2.jar:5.4.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) ~[elasticsearch-5.4.2.jar:5.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

```
What should i do ?

**Comment by marevol** [comment]
`--hostname elasticsearch` may be needed on your environment.
For docker support, we are working on refactoring.
So, it'll be improved in future release.

**Comment by boyoyon8** [comment]
Thanks! I was able to successfully start by this command.

```
docker run -d -p 8080:8080 --name fess --hostname elasticsearch codelibs/fess:latest
```
>So, it'll be improved in future release.
That's sound good. I'm so excited.
