### ISSUE TITLE
Erros in fess-suggest.log

### ISSUE THREAD

**Issue by micakovic** [codelibs/fess#1319]
Do these errors suggest why this is happening and how to address the issue?

    org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
    Failed to initialize the container.

[Path]
smart/cooldeploy-autoregister.xml

[Namespace]
null

[Included by]
app.xml
at
    org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.7.5.jar:?]

at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.7.5.jar:?]

at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.5.jar:?]

at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]

at

org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.7.5.jar:?]

at org.codelibs.fess.exec.SuggestCreator.main(SuggestCreator.java:109) [classes/:?]
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest

at

org.lastaflute.core.smartdeploy.RomanticJobCreator.isWebResource(RomanticJobCreator.java:145) ~[lastaflute-1.0.0-RC6.jar:?]

at
    org.lastaflute.core.smartdeploy.RomanticJobCreator.checkWebReference(RomanticJobCreator.java:121) ~[lastaflute-1.0.0-RC6.jar:?]
	at org.lastaflute.core.smartdeploy.RomanticJobCreator.createComponentDef(RomanticJobCreator.java:76) ~[lastaflute-1.0.0-RC6.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.createComponentDef(CoolComponentAutoRegister.java:108) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.processClass(CoolComponentAutoRegister.java:93) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.traverseFileSystem(ClassTraversal.java:105) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.traverseFileSystem(ClassTraversal.java:102) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.forEach(ClassTraversal.java:45) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.LdiResourcesUtil$FileSystemResources.forEach(LdiResourcesUtil.java:184) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.registerAll(CoolComponentAutoRegister.java:60) ~[lasta-di-0.7.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:83) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
	... 4 more

**Comment by marevol** [comment]
Could you provide details to reproduce it?

**Comment by micakovic** [comment]
Triggering Suggest Indexer Job Scheduler always produces this in about 8 second after starting.



2017-10-28 07:36:33,394 [main] INFO  ...Loading specified properties and get by the key: fess_env_suggest.properties, lasta_di.smart.deploy.mode
2017-10-28 07:36:33,399 [main] INFO  ...Setting smart deploy mode: cool
2017-10-28 07:36:33,419 [main] INFO  ...Reading lasta_di.xml
2017-10-28 07:36:33,497 [main] INFO  ...Reading   redefiner.xml
2017-10-28 07:36:33,561 [main] INFO  ...Reading   smartdeploy.xml
2017-10-28 07:36:33,586 [main] INFO  ...Reading     smart/cooldeploy.xml
2017-10-28 07:36:33,627 [main] INFO  ...Reading app.xml
2017-10-28 07:36:33,633 [main] INFO  ...Reading   convention.xml
2017-10-28 07:36:33,639 [main] INFO  ...Reading     embedded_convention.xml
2017-10-28 07:36:33,652 [main] INFO  ...Reading   lastaflute_director.xml
2017-10-28 07:36:33,757 [main] INFO  ...Reading   fess.xml
2017-10-28 07:36:33,762 [main] INFO  ...Reading     fess_config.xml
2017-10-28 07:36:33,772 [main] INFO  ...Reading     fess_ds.xml
2017-10-28 07:36:33,807 [main] INFO  ...Reading     esflute_config.xml
2017-10-28 07:36:33,811 [main] INFO  ...Reading       esclient.xml
2017-10-28 07:36:34,098 [main] INFO  ...Reading     esflute_user.xml
2017-10-28 07:36:34,103 [main] INFO  ...Reading       esclient.xml (recycle)
2017-10-28 07:36:34,122 [main] INFO  ...Reading     esflute_log.xml
2017-10-28 07:36:34,126 [main] INFO  ...Reading       esclient.xml (recycle)
2017-10-28 07:36:34,203 [main] INFO  ...Reading smart/cooldeploy-autoregister.xml
2017-10-28 07:36:34,209 [main] INFO  ...Reading   convention.xml (recycle)
2017-10-28 07:36:34,209 [main] INFO  ...Reading   creator.xml
2017-10-28 07:36:34,213 [main] INFO  ...Reading     convention.xml (recycle)
2017-10-28 07:36:34,213 [main] INFO  ...Reading     customizer.xml
2017-10-28 07:36:34,218 [main] INFO  ...Reading       lastafw_customizer.xml
2017-10-28 07:36:34,229 [main] INFO  ...Reading       embedded_customizer.xml
2017-10-28 07:36:34,234 [main] INFO  ...Reading         tx_customizer.xml
2017-10-28 07:36:34,248 [main] INFO  ...Reading     my_creator.xml
2017-10-28 07:36:34,253 [main] INFO  ...Reading     lastafw_creator.xml
2017-10-28 07:36:34,257 [main] INFO  ...Reading       convention.xml (recycle)
2017-10-28 07:36:34,257 [main] INFO  ...Reading       customizer.xml (recycle)
2017-10-28 07:36:34,268 [main] INFO  ...Reading     embedded_creator.xml
2017-10-28 07:36:34,272 [main] INFO  ...Reading       convention.xml (recycle)
2017-10-28 07:36:34,272 [main] INFO  ...Reading       customizer.xml (recycle)
2017-10-28 07:36:34,278 [main] INFO  ...Reading   customizer.xml (recycle)
2017-10-28 07:36:34,445 [main] INFO  [Objective Config]
2017-10-28 07:36:34,445 [main] INFO   fess_config.properties extends [fess_env_suggest.properties]
2017-10-28 07:36:34,445 [main] INFO   checkImplicitOverride=true, propertyCount=395
2017-10-28 07:36:34,735 [main] INFO  no modules loaded
2017-10-28 07:36:34,736 [main] INFO  loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2017-10-28 07:36:34,736 [main] INFO  loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2017-10-28 07:36:34,736 [main] INFO  loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2017-10-28 07:36:34,736 [main] INFO  loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
2017-10-28 07:36:34,736 [main] INFO  loaded plugin [org.elasticsearch.transport.Netty3Plugin]
2017-10-28 07:36:34,736 [main] INFO  loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2017-10-28 07:36:38,016 [main] ERROR Suggest creator does not work correctly.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
smart/cooldeploy-autoregister.xml

[Namespace]
null

[Included by]
app.xml
* * * * * * * * * */
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.7.5.jar:?]
	at org.codelibs.fess.exec.SuggestCreator.main(SuggestCreator.java:109) [classes/:?]
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at org.lastaflute.core.smartdeploy.RomanticJobCreator.isWebResource(RomanticJobCreator.java:145) ~[lastaflute-1.0.0-RC6.jar:?]
	at org.lastaflute.core.smartdeploy.RomanticJobCreator.checkWebReference(RomanticJobCreator.java:121) ~[lastaflute-1.0.0-RC6.jar:?]
	at org.lastaflute.core.smartdeploy.RomanticJobCreator.createComponentDef(RomanticJobCreator.java:76) ~[lastaflute-1.0.0-RC6.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.createComponentDef(CoolComponentAutoRegister.java:108) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.processClass(CoolComponentAutoRegister.java:93) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.traverseFileSystem(ClassTraversal.java:105) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.traverseFileSystem(ClassTraversal.java:102) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.forEach(ClassTraversal.java:45) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.LdiResourcesUtil$FileSystemResources.forEach(LdiResourcesUtil.java:184) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.registerAll(CoolComponentAutoRegister.java:60) ~[lasta-di-0.7.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:83) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at org.lastaflute.core.smartdeploy.RomanticJobCreator.isWebResource(RomanticJobCreator.java:145) ~[lastaflute-1.0.0-RC6.jar:?]
	at org.lastaflute.core.smartdeploy.RomanticJobCreator.checkWebReference(RomanticJobCreator.java:121) ~[lastaflute-1.0.0-RC6.jar:?]
	at org.lastaflute.core.smartdeploy.RomanticJobCreator.createComponentDef(RomanticJobCreator.java:76) ~[lastaflute-1.0.0-RC6.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.createComponentDef(CoolComponentAutoRegister.java:108) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.processClass(CoolComponentAutoRegister.java:93) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.traverseFileSystem(ClassTraversal.java:105) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.traverseFileSystem(ClassTraversal.java:102) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.ClassTraversal.forEach(ClassTraversal.java:45) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.util.LdiResourcesUtil$FileSystemResources.forEach(LdiResourcesUtil.java:184) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.smart.cool.CoolComponentAutoRegister.registerAll(CoolComponentAutoRegister.java:60) ~[lasta-di-0.7.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:83) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.5.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
	... 4 more
2017-10-28 07:36:38,029 [main] INFO  Finished suggestCreator.

**Comment by micakovic** [comment]
I tries this to see if it helps: delete suggest index; delete all hidden .suggest* indexes. Restart Fess and rerun suggest indexer front job. Same error.

**Comment by marevol** [comment]
I could not reproduce it. Need more info. ex. OS, Version, and so on...
Is it reproduced in a clean environment?

**Comment by micakovic** [comment]
I'm not entirely sure how this made its way into config, but I must have introduced myself it at some point.

In fess_env_suggest.properties I had lasta_di.smart.deploy.mode set to cool. I compared the the same file in the repository with the fine on my file system, and saw that the repo file has this setting to warm. 

Changing this to warm, restarting Fess, and restarting the suggest cron job solves the issue.
