### ISSUE TITLE
The url may not be valid

### ISSUE THREAD

**Issue by j8** [codelibs/fess#1320]
I receive URL may not be valid error. I try to index coindesk.com. Any idea?

org.codelibs.fess.crawler.exception.CrawlingAccessException: The url may not be valid: https://www.coindesk.com/ https://www.coindesk.com/
at org.codelibs.fess.crawler.client.http.HcHttpClient.doGet(HcHttpClient.java:579)
at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:135)
at org.codelibs.fess.crawler.client.FaultTolerantClient.execute(FaultTolerantClient.java:67)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:164)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 25: https://www.coindesk.com/ https://www.coindesk.com/
at java.net.URI.create(URI.java:852)
at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
at org.codelibs.fess.crawler.client.http.HcHttpClient.doGet(HcHttpClient.java:577)
... 4 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 25: https://www.coindesk.com/ https://www.coindesk.com/
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.checkChars(URI.java:3021)
at java.net.URI$Parser.parseHierarchical(URI.java:3105)
at java.net.URI$Parser.parse(URI.java:3053)
at java.net.URI.<init>(URI.java:588)
at java.net.URI.create(URI.java:850)
... 6 more

**Comment by marevol** [comment]
The waning message is logged if url of <a href=> is invalid.
Please check HTML element in the page which contains the warning.
