### ISSUE TITLE
Question : About time setting of scheduler

### ISSUE THREAD

**Issue by mimori1961** [codelibs/fess#1377]
I am useing FESS10.2.
There are Default Crawler and Suggest indexer in Job Scheduler.
Now these are executed at the same time, then it sometimes causes an error.
Is it possible to resolve this error if I let them run and shift it?

fess_crawler_20171129.log
```
...
2017-11-29 00:00:19,242 [main] ERROR Crawler does not work correctly.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
fess.xml

[Namespace]
null

[Included by]
app.xml
* * * * * * * * * */
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
	at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66)
	at org.codelibs.fess.exec.Crawler.main(Crawler.java:188)
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(init) of org.codelibs.fess.helper.SuggestHelper, because org.codelibs.fess.suggest.exception.SuggestSettingsException: Failed to add to array.
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61)
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35)
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:83)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
	... 4 common frames omitted
Caused by: org.codelibs.fess.suggest.exception.SuggestSettingsException: Failed to add to array.
	at org.codelibs.fess.suggest.settings.ArraySettings.addToArrayIndex(ArraySettings.java:133)
	at org.codelibs.fess.suggest.settings.ArraySettings.add(ArraySettings.java:59)
	at org.codelibs.fess.helper.SuggestHelper.lambda$null$1676(SuggestHelper.java:93)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.codelibs.fess.helper.SuggestHelper.lambda$init$1677(SuggestHelper.java:92)
	at org.codelibs.core.stream.StreamUtil$StreamOf.of(StreamUtil.java:56)
	at org.codelibs.fess.helper.SuggestHelper.init(SuggestHelper.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49)
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59)
	... 11 common frames omitted
Caused by: org.elasticsearch.index.engine.DocumentAlreadyExistsException: [fess][a2V5OnN1cHBvcnRlZEZpZWxkc3ZhbHVlOmNvbnRlbnQ=]: document already exists
	at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:421)
	at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:378)
	at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:349)
	at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:545)
	at org.elasticsearch.index.engine.Engine$Create.execute(Engine.java:810)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:237)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:158)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marevol** [comment]
Is it reproduced in Fess 11.4?

**Comment by mimori1961** [comment]
I have not tried it yet.
I will do.
Thank you.
