### ISSUE TITLE
Install instructions unclear for zip version 12.0.1 (ES 6.1.1)

### ISSUE THREAD

**Issue by teufelweich** [codelibs/fess#1464]
When reading [the installation guide](http://fess.codelibs.org/12.0/install/install.html) it stays unclear to me how I am supposed to configure fess and my ES instance.
I'm unable to find `fess_config.properties` to configure the ES cluster name.

Do i need to set my ES address variables in `/fess-12.0.1/bin/fess.in.sh` to 
```
ES_HTTP_URL=http://localhost:9200
ES_TRANSPORT_URL=localhost:9300
FESS_DICTIONARY_PATH=/var/lib/elasticsearch/config/
```
or elsewhere? 

Thanks in advance

**Comment by marevol** [comment]
app/WEB-INF/classes/fess_config.properties

> Do i need to set my ES address variables in /fess-12.0.1/bin/fess.in.sh

Yes.
FESS_DICTIONARY_PATH depends on your ES installation.

**Comment by teufelweich** [comment]
Thanks for the quick answer.

I have set the cluster name in `app/WEB-INF/classes/fess_config.properties`. Then i ran `bin/fess.in.sh` with the correct ES url and `FESS_DICTIONARY_PATH=/var/lib/elasticsearch/config`. This path i have also configured in `/etc/elasticsearch/elasticsearch.yml` and the ES is running.

Unfortunately it crashes nonetheless.
crash log:
 ```
[localhost-startStop-1] WARN  fess_indices/fess.json is not found.                                                                                                                      │
│java.lang.SecurityException: access denied ("java.io.FilePermission" "/var/lib/elasticsearch/config/ja/mapping.txt" "read")                                                                                     │
│       at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_151]                                                                                                      │
│       at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_151]                                                                                                              │
│       at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_151]                                                                                                                    │
│       at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_151]                                                                                                                          │
│       at sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:245) ~[?:1.8.0_151]                                                                                                                        │
│       at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:136) ~[?:1.8.0_151]                                                                                                              │
│       at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:148) ~[?:1.8.0_151]                                                                                                              │
│       at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:212) ~[?:1.8.0_151]                                                                                                      │
│       at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_151]                                                                                                                                     │
│       at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_151]                                                                                                                                     │
│       at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_151]                                                                                                       │
│       at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_151]                                                                                                                                     │
│       at java.nio.file.Files.newBufferedReader(Files.java:2784) ~[?:1.8.0_151]                                                                                                                                 │
│       at org.elasticsearch.index.analysis.Analysis.getWordList(Analysis.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                             │
│       at org.elasticsearch.analysis.common.MappingCharFilterFactory.<init>(MappingCharFilterFactory.java:43) ~[analysis-common-6.1.1.jar:6.1.1]                                                                │
│       at org.elasticsearch.plugins.AnalysisPlugin$1.get(AnalysisPlugin.java:130) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                              │
│       at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:343) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                            │
│       at org.elasticsearch.index.analysis.AnalysisRegistry.buildCharFilterFactories(AnalysisRegistry.java:182) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                │
│       at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:154) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                   │
│       at org.elasticsearch.index.IndexService.<init>(IndexService.java:160) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                                   │
│       at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:361) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                            │
│       at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:448) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                 │
│       at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:404) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                        │
│       at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:439) ~[elasticsearch-6.1.1.jar:6.1.1]                                         │
│       at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                             │
│       at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:640) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                 │
│       at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                         │
│       at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:195) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                     │
│       at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:130) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                  │
│       at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                │
│       at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                  │
│       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) ~[elasticsearch-6.1.1.jar:6.1.1]                                                         │
│       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) ~[elasticsearch-6.1.1.jar:6.1.1]        │
│       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) ~[elasticsearch-6.1.1.jar:6.1.1]                │
│       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]                                                                                                         │
│       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]                                                                                                         │
│       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]   
 ```
but `/var/lib/elasticsearch/config/ja/mapping.txt` is readable: 
```
~ # ls /var/lib/elasticsearch/config/mapping.txt -la 
-rw-r--r-- 1 elasticsearch elasticsearch 13101 Jan 26 20:11 /var/lib/elasticsearch/config/mapping.txt
```

**Comment by marevol** [comment]
Did you install ES plugins?

**Comment by teufelweich** [comment]
Yes, they're installed:
```
~ # /usr/share/elasticsearch/bin/elasticsearch-plugin list
analysis-fess
analysis-ja
analysis-synonym
configsync
dataformat
langfield
minhash
```

**Comment by marevol** [comment]
Does rpm or deb package work?

**Comment by teufelweich** [comment]
I really wanted to get it working with the zip method.

I think I've tracked the problem down to this exception.

server_0.log:
```
Jan 27, 2018 2:49:19 PM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Booting the Tomcat: port=8080 contextPath=
Jan 27, 2018 2:49:19 PM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Reflecting configuration to server: config=[tomcat_config.properties]
Jan 27, 2018 2:49:19 PM org.dbflute.tomcat.logging.BootLogger info
INFO:  tomcat.URIEncoding = UTF-8
Jan 27, 2018 2:49:19 PM org.dbflute.tomcat.logging.BootLogger info
INFO:  tomcat.useBodyEncodingForURI = true
Jan 27, 2018 2:49:19 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Jan 27, 2018 2:49:19 PM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Jan 27, 2018 2:49:19 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Jan 27, 2018 2:49:19 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.23
Jan 27, 2018 2:49:19 PM org.dbflute.tomcat.logging.BootLogger info
INFO: ...Initializing webapp of default web.xml with JSP (the servlet found)
Jan 27, 2018 2:49:20 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Jan 27, 2018 2:49:20 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Jan 27, 2018 2:51:06 PM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
WARNING: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [105,476] milliseconds.
Jan 27, 2018 2:51:13 PM org.apache.catalina.core.StandardContext filterStart
SEVERE: Exception starting filter [lastaPrepareFilter]
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
esclient.xml

[Namespace]
null

[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml
* * * * * * * * * */
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
	at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66)
	at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81)
	at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45)
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:136)
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4591)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.FessEsClient, because [fess.20180127] IndexNotFoundException[no such index]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61)
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35)
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
	... 23 more
Caused by: [fess.20180127] IndexNotFoundException[no such index]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:678)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:630)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:586)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:164)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:143)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:76)
	at org.elasticsearch.action.admin.indices.mapping.get.TransportGetMappingsAction.checkBlock(TransportGetMappingsAction.java:53)
	at org.elasticsearch.action.admin.indices.mapping.get.TransportGetMappingsAction.checkBlock(TransportGetMappingsAction.java:37)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:135)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:127)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:105)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:55)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:64)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:54)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1554)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:135)
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1511)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1380)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	... 1 more

Jan 27, 2018 2:51:13 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more Filters failed to start. Full details will be found in the appropriate container log file
Jan 27, 2018 2:51:13 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
```

**Comment by marevol** [comment]
Did you check elasticsearch log file?
Fess seemed not to create fess index.

**Comment by teufelweich** [comment]
In the ES log I'm seeing this when fess crashes:
```
[2018-01-27T16:13:41,956][DEBUG][o.e.c.s.MasterService    ] [fies] processing [create-index [fess.20180127], cause [api]]: execute                                                                               │
[2018-01-27T16:13:41,959][DEBUG][o.e.i.IndicesService     ] [fies] creating Index [[fess.20180127/8R9fFzcNSvaNVzGT2zQvPQ]], shards [5]/[0] - reason [create index]                                               │
[2018-01-27T16:13:41,963][DEBUG][o.e.c.m.MetaDataCreateIndexService] [fies] [fess.20180127] failed to create                                                                                                     │
java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/lib/elasticsearch/conf/ja/mapping.txt" "read")                                                                               │
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_151]                                                                                                      │
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_151]                                                                                                              │
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_151]                                                                                                                    │
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_151]                                                                                                                          │
        at sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:245) ~[?:?]                                                                                                                                │
        at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:136) ~[?:?]                                                                                                                      │
        at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:148) ~[?:?]                                                                                                                      │
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:212) ~[?:?]                                                                                                              │
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_151]                                                                                                                                     │
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_151]                                                                                                                                     │
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_151]                                                                                                       │
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_151]                                                                                                                                     │
        at java.nio.file.Files.newBufferedReader(Files.java:2784) ~[?:1.8.0_151]                                                                                                                                 │
        at org.elasticsearch.index.analysis.Analysis.getWordList(Analysis.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                             │
        at org.elasticsearch.analysis.common.MappingCharFilterFactory.<init>(MappingCharFilterFactory.java:43) ~[?:?]                                                                                            │
        at org.elasticsearch.plugins.AnalysisPlugin$1.get(AnalysisPlugin.java:130) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                              │
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:343) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                            │
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildCharFilterFactories(AnalysisRegistry.java:182) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                │
        at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:154) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                   │
        at org.elasticsearch.index.IndexService.<init>(IndexService.java:160) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                                   │
        at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:361) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                            │
        at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:448) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                 │
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:404) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                        │
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:439) ~[elasticsearch-6.1.1.jar:6.1.1]                                         │
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                             │
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:640) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                                 │
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270) ~[elasticsearch-6.1.1.jar:6.1.1]                                                                         │
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:195) [elasticsearch-6.1.1.jar:6.1.1]                                                                                      │
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:130) [elasticsearch-6.1.1.jar:6.1.1]                                                                                   │
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.1.1.jar:6.1.1]                                                                                 │
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.1.1.jar:6.1.1]                                                                                   │
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) [elasticsearch-6.1.1.jar:6.1.1]                                                          │
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-6.1.1.jar:6.1.1]         │
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-6.1.1.jar:6.1.1]                 │
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]                                                                                                         │
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]                                                                                                         │
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]                                                                                                                                                   │
[2018-01-27T16:13:41,971][DEBUG][o.e.c.s.MasterService    ] [fies] processing [create-index [fess.20180127], cause [api]]: took [15ms] no change in cluster state 
```

How can I check if the fess index was created? And if it wasn't created, how could i create it by hand?

**Comment by marevol** [comment]
fess index is not available because Fess cannot access mapping.txt.
Did you change elasitcsearch settings?

**Comment by marevol** [comment]
I think it is better to try it on a clean environment.
> I added the fess user to the elasticsearch group 

It should not be added.

> java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/lib/elasticsearch/conf/ja/mapping.txt" "read")

conf is not correct.
