### ISSUE TITLE
ConfigSyncService failed to start

### ISSUE THREAD

**Issue by Artjom-Grigorjew** [codelibs/fess#1487]
Hello dear developers,

i have troubleshooting bringing up the elasticsearch cluster in combination with the [codelibs/elasticsearch-configsync](https://github.com/codelibs/elasticsearch-configsync). 

I am using elasticsearch Version 6.1.1 and elasticsearch-configsync version 6.1.1.
I get the following error message:

```
[2018-02-08T18:04:46,909][ERROR][o.c.e.c.s.ConfigSyncService] [******] Failed to start ConfigFileUpdater.
org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/exists] is unauthorized for user [_system]
        at org.elasticsearch.xpack.security.support.Exceptions.authorizationError(Exceptions.java:42) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:589) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.denial(AuthorizationService.java:560) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:168) ~[?:?]
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$authorizeRequest$4(SecurityActionFilter.java:176) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:182) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:176) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:158) ~[?:?]
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:190) ~[?:?]
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:166) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$writeAuthToContext$23(AuthenticationService.java:453) ~[?:?]
at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.writeAuthToContext(AuthenticationService.java:462) ~[?:?]
at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$handleNullToken$16(AuthenticationService.java:355) ~[?:?]
at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.handleNullToken(AuthenticationService.java:362) ~[?:?]
```

I am using xpack for the elasticsearch installation and the mentioned user _system is a internal xpack user. 

Is this a known issue? Do you maybe had such behaviour in the past. Meanwhile i would dig into it and search for the solution.

Best regards.

**Comment by Artjom-Grigorjew** [comment]
Unfortunately not yet. I would try it installing without xpack. Then i would give feedback in this issue and ask the devs from xpack.
Btw. thx for formatting the stacktrace. :-)

**Comment by acossette1979** [comment]
Hi did you find to to fix it ?
Are you using user password by add elasticsearch.user = user & elasticsearch.password = passed ?

**Comment by acossette1979** [comment]
@marevol It is working without x-pack, but we need to connect to a production cluster with x-pack. (to answer @Artjom-Grigorjew).

**Comment by acossette1979** [comment]
@marevol here the response from Elasticsearch team.

It doesn't look like the config sync plugin is compatible with X-Pack security.
I would suggest that you raise the issue with the config sync authors.

**Comment by marevol** [comment]
Thank you for checking it, but we have no plan to support x-pack security at the moment.
If you need more supports, please contact [Commercial Support](https://www.n2sm.net/en/support/fess_support.html).

**Comment by acossette1979** [comment]
I did send my inquiries to your commercial support.  Hope that we can resolve this issue soon.
Thanks for the follow-up.
