### ISSUE TITLE
Fresh install Fess12 with Elasticsearch6.1.1, shows can not find this page on webpage

### ISSUE THREAD

**Issue by PakanAngel** [codelibs/fess#1505]
As mentioned in the title have installed a Fess12 on Elasticsearch 6.1.1, also installed all the plugins for fess correctly. I have also added the config path for sync config to Elasticsearch's settings.
After starting Elasticsearch and Fess can't access the admin panel via the web browser. I constantly get the message this web page can not be found. 
Fess log files are included. 
Any instruction to solve this issue is appreciated. 

[fess.log](https://github.com/codelibs/fess/files/1724510/fess.log)
[server_0.log](https://github.com/codelibs/fess/files/1724512/server_0.log)

**Comment by marevol** [comment]
Fess could not connect to elasticsearch.
What is your elasticsearch.yml? Did you change a cluster name?
and also check elasticsearch.log.

**Comment by PakanAngel** [comment]
I did not change anything extra.
The elasticsearch.yml is attached
[elasticsearch.yml.txt](https://github.com/codelibs/fess/files/1725752/elasticsearch.yml.txt)

**Comment by PakanAngel** [comment]
Here is the elasticsearch log file. It  seems there is a problem with the config sync.
[elasticsearch.log](https://github.com/codelibs/fess/files/1725760/elasticsearch.log)

**Comment by marevol** [comment]
You missed analysis-synonym plugin.
See [Installation Guide](https://fess.codelibs.org/12.0/install/install.html).

**Comment by PakanAngel** [comment]
Unfortunately it wasn't the case. But I have added the analysis-synonym plugin once again and restarted the bot services still get the same error: page can not be found.
In the screen below you see the list of added plugins. 
![plugin list](https://user-images.githubusercontent.com/26673019/36231013-c5d83d4c-11dc-11e8-8ad0-d88761d4bdd4.JPG)

**Comment by marevol** [comment]
Did you check elasticsearch.log? and check
```
curl localhost:9200
```

**Comment by PakanAngel** [comment]
Have attached it some post earlier. Here is it once again attached. There is an exception error in the elasticsearch.log file but I can not figure out where the problem is and how to solve it.
Also added a screenshot of a query by elasticsearch. 
![elasticsearch working](https://user-images.githubusercontent.com/26673019/36231824-c5eb7cce-11df-11e8-8e21-caa8650fa966.JPG)

[elasticsearch.log](https://github.com/codelibs/fess/files/1725872/elasticsearch.log)

**Comment by marevol** [comment]
elasticsearch.log is not changed. elasticsearch is not restarted...

**Comment by PakanAngel** [comment]
Sorry for the confusion have resent you the same file for the case you missed it,
[elasticsearch2.log](https://github.com/codelibs/fess/files/1725910/elasticsearch2.log)
 did not updated the file here is the updated elasticsearch.log after restarting.

**Comment by marevol** [comment]
Did you also restart Fess and check fess.log?

**Comment by PakanAngel** [comment]
Yes I did restart Fess. 
This warning is continuously repeated in the server_0.log file.

Feb 15, 2018 7:03:41 AM org.apache.catalina.loader.WebappClassLoaderBase checkStateForResourceLoading
INFO: Illegal access: this web application instance has been stopped already. Could not load [io.netty.channel.socket.nio.NioSocketChannel$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [io.netty.channel.socket.nio.NioSocketChannel$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1311)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1299)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1158)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe.<init>(NioSocketChannel.java:463)
        at io.netty.channel.socket.nio.NioSocketChannel.newUnsafe(NioSocketChannel.java:460)
        at io.netty.channel.socket.nio.NioSocketChannel.newUnsafe(NioSocketChannel.java:50)
        at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:80)
        at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
        at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:55)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:98)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:88)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:81)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:74)
        at jdk.internal.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at java.base/java.lang.Class.newInstance(Class.java:558)
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
        at org.elasticsearch.transport.netty4.Netty4Transport.initiateChannel(Netty4Transport.java:254)
        at org.elasticsearch.transport.netty4.Netty4Transport.initiateChannel(Netty4Transport.java:82)
        at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:604)
        at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:122)
        at org.elasticsearch.transport.TransportService.openConnection(TransportService.java:346)
        at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:407)
        at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:357)
        at org.elasticsearch.client.transport.TransportClientNodesService$ScheduledNodeSampler.run(TransportClientNodesService.java:390)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by marevol** [comment]
Kill all java process, delete log files and then start elasticsearch and fess.

**Comment by PakanAngel** [comment]
I have killed Elasticsearch and Fess and deleted all logs of both services and then restarted them both. 
This is the result of new log files. 
[elasticsearch.log](https://github.com/codelibs/fess/files/1726728/elasticsearch.log)
[fess.log](https://github.com/codelibs/fess/files/1726729/fess.log)

**Comment by marevol** [comment]
Elasticsearch looks fine. 
Fess does not seem to connect to Elasticsearch.
What is settings you changed in Fess?

**Comment by PakanAngel** [comment]
Did not change anything just added the sync config path and thats it.

**Comment by marevol** [comment]
Did you install rpm package?

**Comment by PakanAngel** [comment]
yes

**Comment by PakanAngel** [comment]
Do you suggest me to install Fess11 instead or should I stick with Fess12 and try to solve this issue?

**Comment by marevol** [comment]
I think that Fess 11.4 might be the same if the problem is a network configuration.
You can check debug logs to change the following setting to debug in /usr/share/fess/bin/fess.in.sh:
```
FESS_JAVA_OPTS="$FESS_JAVA_OPTS -Dfess.log.level=warn"
```

For Java9, travis tests is passed.

**Comment by PakanAngel** [comment]
It's already set to the mentioned setting by default.

**Comment by marevol** [comment]
The cause may be Java 9.
I think that it's better to use Java 8.

**Comment by PakanAngel** [comment]
Thank you. I have reinstalled the system to reset any network misconfiguration. And now it works fine. Maybe Java9 caused all the issue.
