### ISSUE TITLE
ContentNotFoundException

### ISSUE THREAD

**Issue by gilreginiano** [codelibs/fess#1577]
Hi,
Just Configured fileserver crawler, also added file authentication, but no luck.

i'm getting error:
org.codelibs.fess.exception.ContentNotFoundException: Not Found: file:////fileserver/share

2018-03-26 10:55:42,390 [DataStoreCrawler] INFO  No crawling target urls.
2018-03-26 10:55:42,422 [WebFsCrawler] INFO  no modules loaded
2018-03-26 10:55:42,422 [WebFsCrawler] INFO  loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2018-03-26 10:55:42,422 [WebFsCrawler] INFO  loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2018-03-26 10:55:42,422 [WebFsCrawler] INFO  loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2018-03-26 10:55:42,422 [WebFsCrawler] INFO  loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
2018-03-26 10:55:42,423 [WebFsCrawler] INFO  loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018-03-26 10:55:42,460 [WebFsCrawler] INFO  Connected to localhost:9300
2018-03-26 10:55:42,525 [WebFsCrawler] INFO  Target Path: file:////fileserver/share
2018-03-26 10:55:42,582 [Crawler-20180326105536-1-3] INFO  Crawling URL: file:////fileserver/share
2018-03-26 10:55:52,545 [IndexUpdater] INFO  Processing no docs (Doc:{access 2ms}, Mem:{used 141MB, heap 194MB, max 494MB})
2018-03-26 10:56:02,538 [IndexUpdater] INFO  Processing no docs (Doc:{access 3ms}, Mem:{used 141MB, heap 194MB, max 494MB})
2018-03-26 10:56:12,538 [IndexUpdater] INFO  Processing no docs (Doc:{access 3ms}, Mem:{used 141MB, heap 194MB, max 494MB})
2018-03-26 10:56:13,683 [WebFsCrawler] INFO  [EXEC TIME] crawling time: 31277ms
2018-03-26 10:56:22,537 [IndexUpdater] INFO  Processing no docs (Doc:{access 2ms}, Mem:{used 141MB, heap 194MB, max 494MB})
2018-03-26 10:56:22,537 [IndexUpdater] INFO  [EXEC TIME] index update time: 18ms
2018-03-26 10:56:22,565 [main] INFO  Finished Crawler
2018-03-26 10:56:22,601 [main] INFO  [CRAWL INFO] DataCrawlEndTime=2018-03-26T10:55:42.390+0300,CrawlerEndTime=2018-03-26T10:56:22.566+0300,WebFsCrawlExecTime=31277,CrawlerStatus=true,CrawlerStartTime=2018-03-26T10:55:42.346+0300,WebFsCrawlEndTime=2018-03-26T10:56:22.565+0300,WebFsIndexExecTime=18,WebFsIndexSize=0,CrawlerExecTime=40220,DataCrawlStartTime=2018-03-26T10:55:42.376+0300,WebFsCrawlStartTime=2018-03-26T10:55:42.374+0300
2018-03-26 10:56:27,609 [main] INFO  Disconnected to elasticsearch:localhost:9300
2018-03-26 10:56:28,856 [main] INFO  Destroyed LaContainer.

what i'm missing?

Fess Properties:
suggest.searchlog=true
suggest.document=true
crawling.incremental=true
failure.countthreshold=-1
csv.file.encoding=UTF-8
search.log=true
purge.suggest.searchlog.day=30
ldap.memberof.attribute=memberOf
purge.joblog.day=-1
purge.by.bots=Crawler,crawler,Bot,bot,Slurp,Yeti,Baidu,Steeler,ichiro,hotpage,Feedfetcher,ia_archiver,Y!J-BRI,Google Desktop,Seznam,Tumblr,YandexBot,Chilkat,CloudFront,Mediapartners,MSIE 6
crawling.thread.count=5
day.for.cleanup=3
result.collapsed=false
web.api.popularword=true
login.link.enabled=true
thumbnail.enabled=true
append.query.parameter=false
user.favorite=false
purge.userinfo.day=-1
web.api.json=true
login.required=false
user.info=true
purge.searchlog.day=-1

System Properties:
java.vendor=Oracle Corporation
sun.java.launcher=SUN_STANDARD
catalina.base=/var/tmp/fess/webapp
fess.foreground=yes
sun.nio.ch.bugLevel=
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
groovy.use.classvalue=true
catalina.useNaming=false
log4j.shutdownHookEnabled=false
os.name=Linux
sun.boot.class.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/jfr.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/classes
java.vm.specification.vendor=Oracle Corporation
java.runtime.version=1.8.0_161-b14
user.name=fess
fess=
user.language=en
sun.boot.library.path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/amd64
log4j.skipJansi=true
fess.conf.path=/etc/fess
jna.nosys=true
java.version=1.8.0_161
user.timezone=Asia/Jerusalem
sun.arch.data.model=64
fess.context.path=/
fess.temp.path=/var/tmp/fess
java.endorsed.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/endorsed
sun.cpu.isalist=
sun.jnu.encoding=UTF-8
file.encoding.pkg=sun.io
file.separator=/
java.specification.name=Java Platform API Specification
java.class.version=52.0
user.country=US
java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre
java.vm.info=mixed mode
os.version=3.10.0-693.21.1.el7.x86_64
io.netty.recycler.maxCapacityPerThread=0
path.separator=:
java.vm.version=25.161-b14
fess.dictionary.path=/var/lib/elasticsearch/config/
fess.product.version=12.1
fess.var.path=/var/lib/fess
java.awt.printerjob=sun.print.PSPrinterJob
sun.io.unicode.encoding=UnicodeLittle
awt.toolkit=sun.awt.X11.XToolkit
fess.es.dir=/usr/share/elasticsearch/
log4j2.disable.jmx=true
io.netty.noKeySetOptimization=true
user.home=/var/lib/fess
java.specification.vendor=Oracle Corporation
java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
java.vendor.url=http://java.oracle.com/
java.vm.vendor=Oracle Corporation
java.runtime.name=OpenJDK Runtime Environment
fess.log.path=/var/log/fess
sun.java.command=org.codelibs.fess.FessBoot
java.class.path=/etc/fess:/usr/share/fess/lib/classes
fess.home=/usr/share/fess
java.vm.specification.name=Java Virtual Machine Specification
catalina.home=/var/tmp/fess/webapp
java.vm.specification.version=1.8
sun.cpu.endian=little
sun.os.patch.level=unknown
java.awt.headless=true
java.io.tmpdir=/var/tmp/fess
fess.log.name=fess
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
fess.log.level=warn
lasta.env=web
tomcat.config.path=tomcat_config.properties
fess.webapp.path=/usr/share/fess/app
os.arch=amd64
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre/lib/ext:/usr/java/packages/lib/ext
fess.version=12.1.1
user.dir=/usr/share/fess
line.separator=

java.vm.name=OpenJDK 64-Bit Server VM
jdk.io.permissionsUseCanonicalPath=true
file.encoding=UTF-8
fess.es.transport_addresses=localhost:9300
java.specification.version=1.8
fess.es.http_address=http://localhost:9200
io.netty.noUnsafe=true
fess.port=8080

**Comment by marevol** [comment]
* file://... is file system crawling.
* smb://... is shared folder/file server crawling.

Is your setting correct? 
I think it's `smb://fileserver/share/`.

**Comment by gilreginiano** [comment]
I'm tried to config smb:// but no luck.


jcifs.smb.SmbException
--

org.codelibs.fess.crawler.exception.CrawlingAccessException: Could not access smb://fileserver/share
at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:360)
at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:195)
at org.codelibs.fess.crawler.client.smb.SmbClient.doGet(SmbClient.java:178)
at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:142)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:164)
at java.lang.Thread.run(Thread.java:748)
Caused by: jcifs.smb.SmbException: Failed to connect to server
java.net.UnknownHostException: ecpfs
at jcifs.UniAddress.getAllByName(UniAddress.java:315)
at jcifs.smb.SmbFile.getFirstAddress(SmbFile.java:865)
at jcifs.smb.SmbFile.connect(SmbFile.java:955)
at jcifs.smb.SmbFile.connect0(SmbFile.java:881)
at jcifs.smb.SmbFile.getType(SmbFile.java:1286)
at jcifs.smb.SmbFile.doEnum(SmbFile.java:1737)
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1719)
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1652)
at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:339)
at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:195)
at org.codelibs.fess.crawler.client.smb.SmbClient.doGet(SmbClient.java:178)
at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:142)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:164)
at java.lang.Thread.run(Thread.java:748)

at jcifs.smb.SmbFile.connect0(SmbFile.java:883)
at jcifs.smb.SmbFile.getType(SmbFile.java:1286)
at jcifs.smb.SmbFile.doEnum(SmbFile.java:1737)
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1719)
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1652)
at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:339)

**Comment by marevol** [comment]
> I think it's `smb://fileserver/share/`.

/ is missing.

**Comment by gilreginiano** [comment]
still the same problem,

org.codelibs.fess.crawler.exception.CrawlingAccessException: Could not access smb://fileserver/share/
at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:360)
at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:195)
at org.codelibs.fess.crawler.client.smb.SmbClient.doGet(SmbClient.java:178)
at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:142)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:164)
at java.lang.Thread.run(Thread.java:748)
Caused by: jcifs.smb.SmbException: Failed to connect to server
java.net.UnknownHostException: ecpfs
at jcifs.UniAddress.getAllByName(UniAddress.java:315)
at jcifs.smb.SmbFile.getFirstAddress(SmbFile.java:865)
at jcifs.smb.SmbFile.connect(SmbFile.java:955)
at jcifs.smb.SmbFile.connect0(SmbFile.java:881)
at jcifs.smb.SmbFile.getType(SmbFile.java:1286)
at jcifs.smb.SmbFile.doEnum(SmbFile.java:1737)
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1719)
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1652)
at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:339)
at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:195)
at org.codelibs.fess.crawler.client.smb.SmbClient.doGet(SmbClient.java:178)
at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:142)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:164)
at java.lang.Thread.run(Thread.java:748)

at jcifs.smb.SmbFile.connect0(SmbFile.java:883)
at jcifs.smb.SmbFile.getType(SmbFile.java:1286)
at jcifs.smb.SmbFile.doEnum(SmbFile.java:1737)
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1719)
at jcifs.smb.SmbFile.listFiles(SmbFile.java:1652)

**Comment by gilreginiano** [comment]
ok i found the problem.
writing full fqdn of the server. fileserver.domain.com
and now it's works!

thanks a a lot!!
