### ISSUE TITLE
Plain text passwords are disabled

### ISSUE THREAD

**Issue by UedaHideki** [codelibs/fess#1588]
I use fess 12.11 and try to crawl to server/location with smb.
But RuntimeException occuers as follows, crawl fails.

```
2018-04-04 16:40:39,752 [Crawler-FkmOj2IBGLQzGRDegF8W-1-1] INFO  Crawling URL: smb://server/location/
2018-04-04 16:40:39,865 [Crawler-FkmOj2IBGLQzGRDegF8W-1-1] ERROR Crawling Exception at smb://server/location/
java.lang.RuntimeException: Plain text passwords are disabled
	at jcifs.smb.SmbComTreeConnectAndX.writeParameterWordsWireFormat(SmbComTreeConnectAndX.java:129) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.AndXServerMessageBlock.writeAndXWireFormat(AndXServerMessageBlock.java:94) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.AndXServerMessageBlock.writeAndXWireFormat(AndXServerMessageBlock.java:166) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.AndXServerMessageBlock.encode(AndXServerMessageBlock.java:65) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbTransport.doSend(SmbTransport.java:445) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.util.transport.Transport.sendrecv(Transport.java:67) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbTransport.send(SmbTransport.java:661) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbSession.sessionSetup(SmbSession.java:316) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbSession.send(SmbSession.java:218) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:176) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbTree.send(SmbTree.java:74) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbTransport.getDfsReferrals(SmbTransport.java:709) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.Dfs.getTrustedDomains(Dfs.java:66) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.Dfs.resolve(Dfs.java:167) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:903) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbFile.connect(SmbFile.java:958) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbFile.connect0(SmbFile.java:881) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbFile.queryPath(SmbFile.java:1339) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbFile.exists(SmbFile.java:1421) ~[jcifs-1.3.18.3.jar:?]
	at jcifs.smb.SmbFile.isFile(SmbFile.java:1508) ~[jcifs-1.3.18.3.jar:?]
	at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:239) ~[fess-crawler-2.1.1.jar:?]
	at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:195) ~[fess-crawler-2.1.1.jar:?]
	at org.codelibs.fess.crawler.client.smb.SmbClient.doGet(SmbClient.java:178) ~[fess-crawler-2.1.1.jar:?]
	at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:142) ~[fess-crawler-2.1.1.jar:?]
	at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:164) [fess-crawler-2.1.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162] 
```

Could I set the property "jcifs.smb.client.disablePlainTextPasswords=false"?
I tried the setting in the following files, but no effect.
     fess.in.bat, project.properties, system.properties

**Comment by marevol** [comment]
JVM options for Crawler are jvm.crawler.options in fess_config.properties.

**Comment by UedaHideki** [comment]
Thank your help. 
I edit "fess_config.properties", behavior chages.
But, it occur the following Exception.

>
