### ISSUE TITLE
Fess 12.1.1 Need Elasticsearch Plugins with sha512

### ISSUE THREAD

**Issue by seshaid** [codelibs/fess#1621]
Thanks a lot for your hardwork and build FESS with many usefully features.  Can you help me to install Elasticsearch Plugins into fess 12.1.1 with sha512
 
**_Note : Iam Using ES 6.2.2 with deb package installer_**

Case #1
iam trying to running this code 
_**/usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-fess:6.1.0**_

and output is :
-> Downloading org.codelibs:elasticsearch-analysis-fess:6.1.0 from maven central
[=================================================] 100%?? 
Warning: sha512 not found, falling back to sha1. This behavior is deprecated and will be removed in a future release. Please update the plugin to use a sha512 checksum.
Exception in thread "main" java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm, isolated]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:297)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:184)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:571)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

Case #2
and then i also trying check the elasticsearch plugins with this command :
/usr/share/elasticsearch/bin/elasticsearch-plugin list

and the result dont appear installed plugins into my fess.

Can you help me?
thanks a lot

**Comment by marevol** [comment]
SHA512 will be supported in future release.
The installed plugin version seems to be wrong.
See [Install Guide](https://fess.codelibs.org/12.1/install/install.html#using-rpm-package).

**Comment by seshaid** [comment]
Thanks a lot @marevol . This is work for me.
I close this issues
