### ISSUE TITLE
EsAccessException while crawling

### ISSUE THREAD

**Issue by EyadA** [codelibs/fess#1738]
Entire site seems to crawl perfectly fine the first time around... if you rerun the crawl scheduler once it is done, I get this error on many pages... if I delete everything in the index and re-crawl again, no errors.. if I try ti right after it is done, I get the EsAccessException! Running with 200 threads against a standalone ES so this might be why but I am not sure.

```
org.codelibs.fess.crawler.exception.EsAccessException: Failed to insert 20180704000000-1.aHR0cHM6Ly9xYS5jbXBhLWFjcG0uY2Evc2VydmUvZG9jcy9lbGEvZ29vZHByYWN0aWNlc2d1aWRlL3BhZ2VzL21hbmFnZV9yaXNrL21hbmFnZV9yaXNrLWZhY3VsdHktZS5odG1s
at org.codelibs.fess.crawler.service.impl.AbstractCrawlerService.insert(AbstractCrawlerService.java:219)
at org.codelibs.fess.crawler.service.impl.EsDataService.store(EsDataService.java:58)
at org.codelibs.fess.crawler.service.impl.EsDataService.store(EsDataService.java:39)
at org.codelibs.fess.crawler.processor.impl.DefaultResponseProcessor.processResult(DefaultResponseProcessor.java:139)
at org.codelibs.fess.crawler.processor.impl.DefaultResponseProcessor.process(DefaultResponseProcessor.java:68)
at org.codelibs.fess.crawler.CrawlerThread.processResponse(CrawlerThread.java:330)
at org.codelibs.fess.crawler.FessCrawlerThread.processResponse(FessCrawlerThread.java:257)
at org.codelibs.fess.crawler.FessCrawlerThread.isContentUpdated(FessCrawlerThread.java:172)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:155)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Future got interrupted
at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:71)
at org.codelibs.fess.crawler.client.EsClient.get(EsClient.java:207)
at org.codelibs.fess.crawler.service.impl.AbstractCrawlerService.insert(AbstractCrawlerService.java:214)
... 9 more
Caused by: java.lang.InterruptedException
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1039)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:234)
at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:69)
at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:66)
... 11 more```

**Comment by marevol** [comment]
Did you check elasticsearch log file?

**Comment by EyadA** [comment]
I ended up changing the max number of threads and lowering it and the issue doesn't come up as much
