### ISSUE TITLE
Fess Web app not working

### ISSUE THREAD

**Issue by AliAAziz** [codelibs/fess#1847]
```
Exception in thread "elasticsearch[Node 1][generic][T#4]" java.lang.NoClassDefFoundError: org/apache/lucene/index/SegmentReadState
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:109)
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:78)
        at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:208)
        at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:258)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:105)
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:490)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:293)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:268)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:258)
        at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
        at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
        at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1405)
        at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1565)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:481)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:393)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:99)
        at org.elasticsearch.index.shard.IndexShard.openIndexAndRecoveryFromTranslog(IndexShard.java:1332)
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:404)
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:94)
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300)
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:92)
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1606)
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2038)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.lucene.index.SegmentReadState]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1301)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1158)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
        ... 31 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.lucene.index.SegmentReadState]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1311)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1299)
        ... 33 more
Exception in thread "elasticsearch[Node 1][generic][T#2]" Exception in thread "elasticsearch[Node 1][generic][T#3]" java.lang.NoClassDefFoundError: org/apache/lucene/index/SegmentReadState
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:109)
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:78)
        at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:208)
        at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:258)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:105)
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:490)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:293)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:268)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:258)
        at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
        at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
        at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1405)
        at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1565)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:481)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:393)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:99)
        at org.elasticsearch.index.shard.IndexShard.openIndexAndRecoveryFromTranslog(IndexShard.java:1332)
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:404)
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:94)
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300)
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:92)
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1606)
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2038)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "elasticsearch[Node 1][generic][T#1]" java.lang.NoClassDefFoundError: org/apache/lucene/index/SegmentReadState
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:109)
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:78)
        at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:208)
        at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:258)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:105)
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:490)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:293)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:268)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:258)
        at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
        at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
        at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1405)
        at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1565)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:481)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:393)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:99)
        at org.elasticsearch.index.shard.IndexShard.openIndexAndRecoveryFromTranslog(IndexShard.java:1332)
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:404)
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:94)
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300)
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:92)
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1606)
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2038)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.NoClassDefFoundError: org/apache/lucene/index/SegmentReadState
        at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:109)
        at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:78)
        at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:208)
        at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:258)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:105)
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:490)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:293)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:268)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:258)
        at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
        at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156)
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
        at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1405)
        at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1565)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:481)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:393)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:99)
        at org.elasticsearch.index.shard.IndexShard.openIndexAndRecoveryFromTranslog(IndexShard.java:1332)
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:404)
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:94)
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300)
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:92)
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1606)
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2038)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by AliAAziz** [comment]
Getting HTTP404 error on browser

**Comment by marevol** [comment]
See [Installation Guide](https://fess.codelibs.org/12.3/install/index.html).

**Comment by AliAAziz** [comment]
Thanks for reply back but codelibs.org link is not active.

**Comment by marevol** [comment]
It works...
