### ISSUE TITLE
How to configure FESS in Eclipse IDE

### ISSUE THREAD

**Issue by farooqsheikhpk** [codelibs/fess#1853]
@marevol 

Do you have any documentation to configure and debug FESS in Eclipse IDE. 

I am facing issue when run a crawler under Eclipse IDE.  I wan to debug a crawler what is the best way to do that. 

Thanks in advance for all your cooperation. 

```
 `[Job Result]
 beginTime: 2018-10-02 15:17:00.318
 performanceView: 00m00s770ms
 sqlCount: {total=0, selectCB=0, entityUpdate=0, queryUpdate=0, outsideSql=0, procedure=0}
 runtime: Cron4jRuntime:{scriptExecutorJob_9, ping_es, * * * * *, ScriptExecutorJob@run(), params={scheduledJob=ScheduledJob [available=true, crawler=false, createdBy=system, createdTime=0, cronExpression=* * * * *, jobLogging=false, name=Ping Elasticsearch, scriptData=return container.getComponent("pingEsJob").execute();, scriptType=groovy, sortOrder=9, target=all, updatedBy=system, updatedTime=0, docMeta=org.codelibs.fess.es.config.allcommon.EsAbstractEntity$DocMeta@7dcabe22]}}@47a5040a


2018-10-02 15:17:01,115 [job_thumbnail_generate] INFO  ThumbnailGenerator: 
Directory=D:\PROFESSIONAL\aspose\git-repo\fess\src\main\webapp
Options=[java, -cp, WEB-INF\env\thumbnail\resources;WEB-INF\classes;D:\PROFESSIONAL\aspose\git-repo\fess\target\classes;WEB-INF\lib\fess-ds-csv-12.2.0.jar;WEB-INF\lib\fess-ds-db-12.2.0.jar;WEB-INF\lib\fess-ds-elasticsearch-12.2.0.jar;WEB-INF\lib\fess-ds-gitbucket-12.2.0.jar;WEB-INF\lib\fess-ds-json-12.2.0.jar;WEB-INF\env\thumbnail\lib\javax.annotation-api-1.3.1.jar, -Dfess.es.http_address=http://localhost:9201, -Dfess.thumbnail.process=true, -Dfess.log.path=D:\PROFESSIONAL\aspose\git-repo\fess\target\logs, -Dfess.log.name=fess-thumbnail, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -server, -Xmx256m, -XX:MaxMetaspaceSize=128m, -XX:CompressedClassSpaceSize=32m, -XX:-UseGCOverheadLimit, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+UseTLAB, -XX:+DisableExplicitGC, -XX:+HeapDumpOnOutOfMemoryError, -Dgroovy.use.classvalue=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -Djava.io.tmpdir=C:\Users\FAROOQ~1\AppData\Local\Temp\fessTmpDir_lDklobcJIERInKO, org.codelibs.fess.exec.ThumbnailGenerator, --sessionId, lDklobcJIERInKO, --numOfThreads, 1, -p, C:\Users\FAROOQ~1\AppData\Local\Temp\thumbnail_3122709719301558664.properties]
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at java.lang.Class.getDeclaredMethods0(Native Method)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at java.lang.Class.getMethod0(Class.java:3018)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at java.lang.Class.getMethod(Class.java:1784)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2018-10-02 15:17:01,335 [InputStreamThread] DEBUG 	... 7 more
2018-10-02 15:17:01,336 [InputStreamThread] DEBUG Error: A JNI error has occurred, please check your installation and try again
2018-10-02 15:17:01,340 [InputStreamThread] DEBUG Exception in thread "main" 
2018-10-02 15:17:01,354 [job_thumbnail_generate] INFO  ThumbnailGenerator: Exit Code=1 - ThumbnailGenerator Process Output:`
```

**Comment by marevol** [comment]
See https://github.com/codelibs/fess/issues/673#issuecomment-245604901
