### ISSUE TITLE
increase rank by click and count Outlinks

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#1927]
fess can increase rank by click and count Outlinks ??

**Comment by marevol** [comment]
In app.xml, you can add ScoreFunctionBuilder:
```
...
    <component name="queryHelper" class="org.codelibs.fess.helper.QueryHelper">
        <postConstruct name="addBoostFunction">
            <arg>org.elasticsearch.index.query.functionscore.ScoreFunctionBuilders.fieldValueFactorFunction("click_count")
            </arg>
        </postConstruct>
...
    </component>
...
```

**Comment by MajidSafari** [comment]
?

`	<component name="queryHelper" class="org.codelibs.fess.helper.QueryHelper">
		<property name="defaultFacetInfo">facetInfo</property>
		<property name="lowercaseWildcard">false</property>
		<postConstruct name="addHighlightField">
			<arg>"title"</arg>
		</postConstruct>
		<postConstruct name="addHighlightField">
			<arg>"content"</arg>
		</postConstruct>
		<postConstruct name="addQueryRescorer">
			<arg>
				<component class="org.codelibs.fess.score.LtrQueryRescorer" />
			</arg>
		</postConstruct>
	<postConstruct name="addBoostFunction">
            <arg>org.elasticsearch.index.query.functionscore.ScoreFunctionBuilders.fieldValueFactorFunction("click_count")
            </arg>
        </postConstruct>
	</component>`



but   error 

`Exception in thread "elasticsearch[Node 1][generic][T#1]" java.lang.NoClassDefFoundError: org/apache/lucene/codecs/NormsConsumer$1
        at org.apache.lucene.codecs.lucene70.Lucene70NormsFormat.normsConsumer(Lucene70NormsFormat.java:85)
        at org.apache.lucene.index.DefaultIndexingChain.writeNorms(DefaultIndexingChain.java:292)
        at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:129)
        at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:470)
        at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:554)
        at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:719)
        at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3211)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3456)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3421)
        at org.elasticsearch.index.engine.InternalEngine.commitIndexWriter(InternalEngine.java:2375)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:454)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:415)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:110)
        at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1373)
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:425)
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95)
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:302)
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93)
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1645)
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2135)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`
