### ISSUE TITLE
EsRejectedExecutionException occurs

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#1928]
hi when Fess Crawler Crawl https://www.iranketab.ir/tag/77-prix-france-culture

just in page !!!!!

```
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of processing of [1714199521][indices:data/write/bulk[s][p]]: request: BulkShardRequest [[fess.20181129][3]] containing [delete {[fess.update][doc][https:%2F%2Fwww.iranketab.ir%2Ftag%2F129-religious-stories;role=Rguest]}] and a refresh, target allocation id: -7Dlo5S3Qi2-NoPx6AYbHw, primary term: 1 on EsThreadPoolExecutor[name = Node 1/write, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@528921a9[Running, pool size = 32, active threads = 32, queued tasks = 200, completed tasks = 3065930]]
at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:48)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.doExecute(EsThreadPoolExecutor.java:98)
at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:93)
at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:713)
at org.elasticsearch.transport.TransportService.access$000(TransportService.java:82)
```

**Comment by marevol** [comment]
Not a bug.
You need to set a proper settings of Elasticsarch for a performance in your environment.

**Comment by MajidSafari** [comment]
oh , how can set ?

**Comment by marevol** [comment]
Please search EsRejectedExecutionException on Google.

**Comment by MajidSafari** [comment]
tnx
