### ISSUE TITLE
fess.suggest in ver 12.4.3

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#1952]
2019-01-06 14:08:34,984 [main] INFO  Parse words from indexed documents.
2019-01-06 14:08:35,224 [pool-2-thread-1] ERROR Failed to update suggest index.
org.codelibs.fess.suggest.exception.SuggestIndexException: Failed to index from document
	at org.codelibs.fess.suggest.index.SuggestIndexer.indexFromDocument(SuggestIndexer.java:276) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.suggest.index.SuggestIndexer.lambda$indexFromDocument$11(SuggestIndexer.java:299) ~[fess-suggest-6.5.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IndexOutOfBoundsException: Index: 368, Size: 368
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_171]
	at org.codelibs.fess.suggest.index.contents.DefaultContentsParser.parseDocument(DefaultContentsParser.java:144) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.suggest.index.SuggestIndexer.lambda$indexFromDocument$9(SuggestIndexer.java:270) ~[fess-suggest-6.5.2.jar:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_171]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_171]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545) ~[?:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_171]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_171]
	at org.codelibs.fess.suggest.index.SuggestIndexer.indexFromDocument(SuggestIndexer.java:272) ~[fess-suggest-6.5.2.jar:?]
	... 4 more
2019-01-06 14:08:35,229 [main] INFO  Store search logs.
2019-01-06 14:08:35,249 [main] INFO  Switch indices.
2019-01-06 14:08:35,277 [main] INFO  Remove old indices.

**Comment by marevol** [comment]
It'll be fixed in the next release.

**Comment by MajidSafari** [comment]
hi @marevol  when do you release ?

**Comment by marevol** [comment]
maybe next week...
