### ISSUE TITLE
Elasticsearch invalid configuration

### ISSUE THREAD

**Issue by crockpotveggies** [codelibs/fess#1984]
Installed the Debian package and followed installation instructions.

I added the following to the elasticsearch config as stated here: https://fess.codelibs.org/12.3/install/install.html#id1

```
To access from Fess, the following configuration needs to be added to /etc/elasticsearch/elasticsearch.yml

configsync.config_path: /var/lib/elasticsearch/config
```

However when starting elasticsearch it produces an error and fails:
```
Caused by: java.lang.IllegalArgumentException: unknown setting [configsync.config_path] please check that any required plugins are installed, or check the breaking changes docu$
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:476) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:421) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:392) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:363) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:148) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.node.Node.<init>(Node.java:373) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.4.jar:6.5.4]
        ... 6 more
```

Looks like the docs need to be updated?

**Comment by crockpotveggies** [comment]
It also looks like there's an issue with one of the plugins:
```
[2019-01-24T03:15:17,590][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [ksV6BUz] fatal error in thread [main], exiting
java.lang.IllegalAccessError: tried to access class org.elasticsearch.common.logging.ESLoggerFactory from class com.o19s.es.ltr.feature.store.index.IndexFeatureStore
        at com.o19s.es.ltr.feature.store.index.IndexFeatureStore.<clinit>(IndexFeatureStore.java:71) ~[?:?]
        at com.o19s.es.ltr.LtrQueryParserPlugin.getSettings(LtrQueryParserPlugin.java:207) ~[?:?]
        at org.elasticsearch.plugins.PluginsService.lambda$getPluginSettings$0(PluginsService.java:87) ~[elasticsearch-6.5.4.jar:6.5.4]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_201]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_201]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_201]
        at org.elasticsearch.plugins.PluginsService.getPluginSettings(PluginsService.java:87) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.node.Node.<init>(Node.java:355) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.4.jar:6.5.4]
```

**Comment by marevol** [comment]
Did you install proper plugins correctly?
See [Installation Guide](https://fess.codelibs.org/12.4/install/install.html) for Fess 12.4.

**Comment by crockpotveggies** [comment]
Yes as I've already stated I followed the installation instructions which means I ran these commands:
```
$ /usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-fess:6.5.0
$ /usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-analysis-extension:6.5.1
$ /usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-configsync:6.5.0
$ /usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-dataformat:6.5.0
$ /usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-langfield:6.5.0
$ /usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-minhash:6.5.0
$ /usr/share/elasticsearch/bin/elasticsearch-plugin install org.codelibs:elasticsearch-learning-to-rank:6.5.0
```

and restarted elasticsearch.

**Comment by marevol** [comment]
It's not _cat/plugins api...

**Comment by crockpotveggies** [comment]
Sorry can you be more specific for someone who is not an expert on elasticsearch? Is that a folder? Is that a specific HTTP API? As I showed earlier the elasticsearch instance dies instantly on start with the error I posted so I'm unable to query any API.

**Comment by marevol** [comment]
> https://fess.codelibs.org/12.3/install/install.html#id1

The above doc is for Fess 12.3/Elasticsearch 6.4.
I think it's better to remove /usr/share/elasticsearch/plugins/* and install plugins again with Fess 12.4 doc.

cat API is [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html).

> java.lang.IllegalAccessError: tried to access class org.elasticsearch.common.logging.ESLoggerFactory from class com.o19s.es.ltr.feature.store.index.IndexFeatureStore

I think wrong plugins were installed...

**Comment by crockpotveggies** [comment]
I just switched to Docker, the installation process is too complex and error prone for my taste. I need something easily reproducible...thanks for the help.
