### ISSUE TITLE
Crawler for SMB1 throws ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by hara-ak** [codelibs/fess#2022]
I have been a user of Fess 10.0.3 for two SMB servers.(one is old SMB server, another is new Windows10) 
Fess 10.0.3 works well and very useful, thanks a lot.

Now,I am building new Fess 12.5.0,
 Crawler to new Windows10 server works fine. 
 Crawler to old SMB does not start, so I add below setting to "fess_config.properties" 
```
jvm.crawler.options=\ ...
-Djcifs.smb.client.enableSMB2=false\n\
-Djcifs.smb.client.signingPreferred=false\n\
-Djcifs.smb.client.signingEnforced=false\n\
-Djcifs.smb.client.ipcSigningEnforced=false\n\
```
then 12.5.0 Crawler to old SMB starts.

But,crawling in some files(about 30% of the whole files),crawler throws Exception below.
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at jcifs.dcerpc.UnicodeString.toString(UnicodeString.java:88) ~[jcifs-2.1.6.jar:?]
	at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:92) ~[jcifs-2.1.6.jar:?]
	at jcifs.smb.SIDCacheImpl.resolveSids0(SIDCacheImpl.java:108) ~[jcifs-2.1.6.jar:?]
	at jcifs.smb.SIDCacheImpl.resolveSids(SIDCacheImpl.java:139) ~[jcifs-2.1.6.jar:?]
	at jcifs.smb.SmbFile.processAces(SmbFile.java:2188) ~[jcifs-2.1.6.jar:?]
	at jcifs.smb.SmbFile.getSecurity(SmbFile.java:2257) ~[jcifs-2.1.6.jar:?]
	at org.codelibs.fess.crawler.client.smb.SmbClient.processAccessControlEntries(SmbClient.java:330) ~[fess-crawler-2.5.0.jar:?]
	at org.codelibs.fess.crawler.client.smb.SmbClient.getResponseData(SmbClient.java:232) ~[fess-crawler-2.5.0.jar:?]
	at org.codelibs.fess.crawler.client.smb.SmbClient.processRequest(SmbClient.java:160) ~[fess-crawler-2.5.0.jar:?]
	at org.codelibs.fess.crawler.client.smb.SmbClient.doHead(SmbClient.java:390) ~[fess-crawler-2.5.0.jar:?]
	at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:144) ~[fess-crawler-2.5.0.jar:?]
	at org.codelibs.fess.crawler.FessCrawlerThread.isContentUpdated(FessCrawlerThread.java:85) ~[classes/:?]
	at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:155) [fess-crawler-2.5.0.jar:?]
```

Any required setting in Fess12.5.0 for old SMB?

**Comment by marevol** [comment]
we could not reproduce this problem in our environment yet...

**Comment by marevol** [comment]
What is the old SMB server?
