### ISSUE TITLE
fess-xpack plugin issues

### ISSUE THREAD

**Issue by zackhorvath** [codelibs/fess#2032]
Hey all,

I've been running Fess for a bit and have been really enjoying it. I'm currently trialing x-pack for security and SSL and am running into some difficulty following https://github.com/codelibs/fess-xpack.

1. I installed and configured x-pack on my ElasticSearch 6.4.3 cluster.
2. I configured the x-pack passwords and verified that the fess user and role I've created works
3. I configured configsync with the required settings and the cluster starts up fine. I also created the xpack.properties file inside /etc/fess.
4. I downloaded and installed fess-xpack from Maven and use `java -Delasticsearch.version=6.2.4 -jar fess-xpack-12.4.3.0.jar` to install the files, followed by giving ownership of downloaded files to the fess service account and setting chmod to 755. It's also important to note that versions higher than 6.2.4 in the Delasticsearch.version variable will cause the jar to fail since ElasticSearch deprecated the xpack api jar.
5. I convert my certificates from .p12 to JKS and add the following to my esclient.xml and my fess.in.bat:
```
"searchguard.ssl.transport.keystore_type":"JKS",
"searchguard.ssl.transport.keystore_filepath":"/etc/fess/certs/elastic-certificates.jks",
"searchguard.ssl.transport.keystore_password":"$PASSWORD",
"searchguard.ssl.transport.truststore_type":"JKS",
"searchguard.ssl.transport.truststore_filepath":"/etc/fess/certs/elastic-certificates.jks",
"searchguard.ssl.transport.truststore_password":"$PASSWORD"
```

and...

```
JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.trustStore=/etc/fess/certs/elastic-certificates.jks"
JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.trustStorePassword=$PASSWORD"
```
6. I attempt to start Fess but get the following stacktrace:
```
2019-02-26 14:27:25,723 [main] ERROR Failed to initialize Lasta Di.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
esclient.xml

[Namespace]
null

[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml
* * * * * * * * * */
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81) ~[lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45) ~[lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:136) [lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94) [lastaflute-1.0.9.jar:?]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102) [classes/:?]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4491) [classes/:?]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [classes/:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944) [classes/:?]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [classes/:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) [?:?]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944) [classes/:?]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:261) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:370) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.startServer(TomcatBoot.java:681) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:385) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:330) [classes/:?]
	at org.codelibs.fess.FessBoot.main(FessBoot.java:90) [classes/:?]
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.xpack.es.client.XPackFessEsClient, because java.lang.IllegalArgumentException: NamedWriteable [org.elasticsearch.cluster.NamedDiff][persistent_tasks] is already registered for [org.elasticsearch.cluster.ClusterModule$$Lambda$1022/343534938], cannot register [org.elasticsearch.xpack.core.XPackClientPlugin$$Lambda$1030/1423111635]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 42 more
Caused by: java.lang.IllegalArgumentException: NamedWriteable [org.elasticsearch.cluster.NamedDiff][persistent_tasks] is already registered for [org.elasticsearch.cluster.ClusterModule$$Lambda$1022/343534938], cannot register [org.elasticsearch.xpack.core.XPackClientPlugin$$Lambda$1030/1423111635]
	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.<init>(NamedWriteableRegistry.java:91) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:163) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:284) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:128) ~[transport-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:59) ~[x-pack-transport-6.2.4.jar:6.2.4]
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:54) ~[x-pack-transport-6.2.4.jar:6.2.4]
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:50) ~[x-pack-transport-6.2.4.jar:6.2.4]
	at org.codelibs.fess.xpack.es.client.XPackFessEsClient.createTransportClient(XPackFessEsClient.java:49) ~[fess-xpack-12.4.3.0.jar:?]
	at org.codelibs.fess.es.client.FessEsClient.open(FessEsClient.java:280) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 42 more

```
Are there any hints here? I suspect the issue is caused by the x-pack-api-6.2.4.jar being the latest version available and not actually working, or maybe it's because I changed the searchguard settings in esclient to use JKS instead of pem files? I would appreciate being pointed in the right direction!
Also worth noting the bundled ES jar files with Fess point to a higher version than I have. A little bit confused here!

Thank you for all your work!

**Comment by marevol** [comment]
Fess XPack 12.4 supports only elasticsearch 6.5.
For supporting XPack on Fess, if you need more supports, please contact [commercial support](https://www.n2sm.net/en/support/fess_support.html).

**Comment by zackhorvath** [comment]
Thank you! I'll look at upgrading 👍
I put in a request with my org that we look at getting a support contract too, we may be in touch!

Thanks again
