### ISSUE TITLE
NoClassDefFoundError: io/netty/util/concurrent/DeaultPromise$1

### ISSUE THREAD

**Issue by yuuiki** [codelibs/fess#2042]
Hi,
As you recommend for the production we need to have stand elasticsearch not using the one from FESS . I've installed elasticsearch  and following the installation guide .I can access the ES suceessfully now,but when I start the fess , it throws exceptions.

Fess version: 12.4.4
elasticsearch version: 6.5.4

![of o 2376l _ss u g4 4](https://user-images.githubusercontent.com/29880212/54016431-d7673380-41bd-11e9-992a-aaab9f646391.png)
![b9 dg q h q1j y n jcwfr](https://user-images.githubusercontent.com/29880212/54016433-db935100-41bd-11e9-8030-eab5d2d9f233.png)

exception:
```
[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml

	at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81) ~[lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45) ~[lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:136) [lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94) [lastaflute-1.0.9.jar:?]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102) [classes/:?]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4491) [classes/:?]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [classes/:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_172]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944) [classes/:?]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [classes/:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_172]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944) [classes/:?]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:261) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:370) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.startServer(TomcatBoot.java:681) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:385) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:330) [classes/:?]
	at org.codelibs.fess.FessBoot.main(FessBoot.java:90) [classes/:?]
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.FessEsClient, because org.lastaflute.di.exception.ContainerInitFailureException: Elasticsearch (localhost:9300) is not available. Check the state of your Elasticsearch cluster (elasticsearch) in 60959ms.
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 42 more
Caused by: org.lastaflute.di.exception.ContainerInitFailureException: Elasticsearch (localhost:9300) is not available. Check the state of your Elasticsearch cluster (elasticsearch) in 60959ms.
	at org.codelibs.fess.es.client.FessEsClient.waitForYellowStatus(FessEsClient.java:637) ~[classes/:?]
	at org.codelibs.fess.es.client.FessEsClient.open(FessEsClient.java:298) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 42 more
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{dM0sY6zLTLi4Fj1Apsi2JA}{localhost}{127.0.0.1:9300}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:349) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:247) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:60) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:382) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:395) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:384) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:696) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:46) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.codelibs.fess.es.client.FessEsClient.waitForYellowStatus(FessEsClient.java:615) ~[classes/:?]
	at org.codelibs.fess.es.client.FessEsClient.open(FessEsClient.java:298) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 42 more
2019-03-08 15:40:35,197 [elasticsearch[_client_][generic][T#4]] WARN  node {#transport#-1}{dM0sY6zLTLi4Fj1Apsi2JA}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2019-03-08 15:40:40,243 [elasticsearch[_client_][generic][T#2]] WARN  node {#transport#-1}{dM0sY6zLTLi4Fj1Apsi2JA}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2019-03-08 15:40:45,275 [elasticsearch[_client_][generic][T#3]] WARN  node {#transport#-1}{dM0sY6zLTLi4Fj1Apsi2JA}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
```
Could you please advise if I've missed something to install ES into FESS.

**Comment by marevol** [comment]
You need to change a cluster name in fess_config.properties:

    elasticsearch.cluster.name=elasticsearch

**Comment by yuuiki** [comment]
The problem has been solved，thank you very much,
