### ISSUE TITLE
cannot start fess 12.5.1 after rebooting

### ISSUE THREAD

**Issue by yama2k** [codelibs/fess#2043]
I download 12.5.1 zip. and start crawling external directory such as "file:///<host>/<directory>".
There are 1.4M files exists and using 1.4TB disks.
I rebooted fess before crawl completes.
Then fess no longer starts successfully.

Below is latest error
How can I fix this?

```
3月 12, 2019 3:34:18 午後 org.dbflute.tomcat.logging.BootLogger info
情報: ...Booting the Tomcat: port=8080 contextPath=
3月 12, 2019 3:34:21 午後 org.dbflute.tomcat.logging.BootLogger info
情報: ...Reflecting configuration to server: config=[tomcat_config.properties]
3月 12, 2019 3:34:21 午後 org.dbflute.tomcat.logging.BootLogger info
情報:  tomcat.URIEncoding = UTF-8
3月 12, 2019 3:34:21 午後 org.dbflute.tomcat.logging.BootLogger info
情報:  tomcat.useBodyEncodingForURI = true
3月 12, 2019 3:34:23 午後 org.apache.coyote.AbstractProtocol init
情報: Initializing ProtocolHandler ["http-nio-8080"]
3月 12, 2019 3:34:23 午後 org.apache.catalina.core.StandardService startInternal
情報: Starting service [Tomcat]
3月 12, 2019 3:34:23 午後 org.apache.catalina.core.StandardEngine startInternal
情報: Starting Servlet engine: [Apache Tomcat/9.0.14]
3月 12, 2019 3:34:24 午後 org.dbflute.tomcat.logging.BootLogger info
情報: ...Initializing webapp of default web.xml with JSP (the servlet found)
3月 12, 2019 3:35:07 午後 org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
情報: No global web.xml found
3月 12, 2019 3:35:25 午後 org.apache.jasper.servlet.TldScanner scanJars
情報: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
3月 12, 2019 3:37:08 午後 org.apache.catalina.core.StandardContext filterStart
重大: Exception starting filter [lastaPrepareFilter]
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
app.xml

[Namespace]
null
* * * * * * * * * */
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415)
	at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66)
	at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81)
	at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45)
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:136)
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4511)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5157)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1382)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1372)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:907)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1382)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1372)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:907)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:423)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:933)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:398)
	at org.dbflute.tomcat.TomcatBoot.startServer(TomcatBoot.java:681)
	at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:385)
	at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:330)
	at org.codelibs.fess.FessBoot.main(FessBoot.java:90)
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(init) of org.codelibs.fess.helper.LabelTypeHelper, because Failed to execute phase [query], all shards failed
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61)
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41)
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35)
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434)
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
	... 36 more
Caused by: Failed to execute phase [query], all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:133)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:254)
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:101)
	at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$1(InitialSearchPhase.java:209)
	at org.elasticsearch.action.search.InitialSearchPhase$1.doRun(InitialSearchPhase.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```

**Comment by marevol** [comment]
Did you install Fess and Elasticsearch separately?

**Comment by yama2k** [comment]
No. I'm using embedded elasticsearch.  Is that non-recommended way ?

**Comment by marevol** [comment]
Embedded Elasticsearch is not recommended for crawling over 1M files.

**Comment by yama2k** [comment]
Thank you very much. I'll try with separate elasticsearch.
