### ISSUE TITLE
Index not found exception after deleting index

### ISSUE THREAD

**Issue by wumpz** [codelibs/fess#2126]
I deleted (unfortunately) my document index using the dashboard. Now I thought a new crawling process would recreate one. This does not work. 

I also don't know, how to recreate this index. :(

Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.FessEsClient, because [fess.20190523] IndexNotFoundException[no such index [fess.20190523]]
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61) ~[lasta-di-0.8.0-RC2.jar:?]
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.8.0-RC2.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.8.0-RC2.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.8.0-RC2.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.8.0-RC2.jar:?]
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.8.0-RC2.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.8.0-RC2.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.8.0-RC2.jar:?]
        ... 8 more
Caused by: org.elasticsearch.index.IndexNotFoundException: no such index [fess.20190523]
        at org.codelibs.elasticsearch.client.action.HttpGetMappingsAction.lambda$execute$0(HttpGetMappingsAction.java:47) ~[elasticsearch-httpclient-7.0.1.jar:?]
        at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:202) ~[curl4j-1.2.1.jar:?]
        at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:182) ~[curl4j-1.2.1.jar:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
2019-05-23 08:32:15,297 [main] INFO  Destroyed LaContainer.

**Comment by marevol** [comment]
1. Delete fess.* index
2. Restart Fess

Fess create fess.* index if it does not exist.

**Comment by wumpz** [comment]
OK.

It would be nice if this would somehow be supported by your web frontend or somehow mentioned. After that deleting an index is dangerous.

Thx for FESS :)

**Comment by wumpz** [comment]
Fess didn't recreate this index. :(
By the way I using the latest docker image. Maybe there is some difference.

After cleaning all config data and elasticsearch data and restart and reconfiguring all is running now again.
