### ISSUE TITLE
Cannot start Fess.bat because of high disk watermark [90%]

### ISSUE THREAD

**Issue by MeMeLwin** [codelibs/fess#2135]
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];
at org.elasticsearch.cluster.block.ClusterBlocks.indexBlockedException(ClusterBlocks.java:183) ~[elasticsearch-6.5.4.jar:6.5.4]

WARN  high disk watermark [90%] exceeded on [jcXB2ps-Qh-Cq_3_Y1zpow][Node 1][C:\fess-12.4.3\es\node_1\data\nodes\0] free: 2.6gb[5.2%], shards will be relocated away from this node

After getting this error, I can't start fess. 
How can I change the setting? 
I tried the command [ $ curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}' ] but my OS is Window and it didn't work.

My elasticsearch is embedded one in fess. Not external elasticsearch.

**Comment by marevol** [comment]
> Embedded Elasticsearch is not recommended for production use.

See [Installation Guide](https://fess.codelibs.org/13.0/install/install.html).
You need to install an external elasticsearch.

**Comment by MeMeLwin** [comment]
Although I checked the installation guide, the elasticsearch installation and setting are for UNIX env.
I need for Window env.

**Comment by marevol** [comment]
https://fess.codelibs.org/13.0/install/install.html#using-your-elasticsearch-cluster-on-zip-package

**Comment by MeMeLwin** [comment]
I still haven't install external ES. But when I start fess, 404Error.

2019-05-29 09:33:30,365 [main] WARN  Embedded Elasticsearch is running. This configuration is not recommended for production use.
2019-05-29 09:33:59,772 [elasticsearch[Node 1][generic][T#1]] WARN  Cluster service was timeouted.
2019-05-29 09:34:05,975 [main] ERROR Failed to initialize Lasta Di.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
app.xml

[Namespace]
null
* * * * * * * * * */
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81) ~[lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45) ~[lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:136) [lastaflute-1.0.9.jar:?]
	at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94) [lastaflute-1.0.9.jar:?]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102) [classes/:?]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4491) [classes/:?]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [classes/:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_144]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944) [classes/:?]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429) [classes/:?]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [classes/:?]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [?:1.8.0_144]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944) [classes/:?]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:261) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770) [classes/:?]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [classes/:?]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:370) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.startServer(TomcatBoot.java:681) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:385) [classes/:?]
	at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:330) [classes/:?]
	at org.codelibs.fess.FessBoot.main(FessBoot.java:90) [classes/:?]
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(init) of org.codelibs.fess.helper.SuggestHelper, because org.codelibs.fess.suggest.exception.SuggestSettingsException: Failed to delete all from array.
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 36 more
Caused by: org.codelibs.fess.suggest.exception.SuggestSettingsException: Failed to delete all from array.
	at org.codelibs.fess.suggest.settings.ArraySettings.deleteKeyFromArray(ArraySettings.java:151) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.suggest.settings.ArraySettings.delete(ArraySettings.java:70) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.helper.SuggestHelper.init(SuggestHelper.java:105) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 36 more
Caused by: org.codelibs.fess.suggest.exception.SuggesterException: Failed to exec delete by query.
	at org.codelibs.fess.suggest.util.SuggestUtil.deleteByQuery(SuggestUtil.java:242) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.suggest.settings.ArraySettings.deleteKeyFromArray(ArraySettings.java:149) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.suggest.settings.ArraySettings.delete(ArraySettings.java:70) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.helper.SuggestHelper.init(SuggestHelper.java:105) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 36 more
Caused by: org.codelibs.fess.suggest.exception.SuggesterException: failure in bulk execution:
[0]: index [.suggest_array.fess], type [fess], id [a2V5OnN1cHBvcnRlZEZpZWxkc3ZhbHVlOmNvbnRlbnQ=], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
[1]: index [.suggest_array.fess], type [fess], id [a2V5OnN1cHBvcnRlZEZpZWxkc3ZhbHVlOnRpdGxl], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
	at org.codelibs.fess.suggest.util.SuggestUtil.deleteByQuery(SuggestUtil.java:235) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.suggest.settings.ArraySettings.deleteKeyFromArray(ArraySettings.java:149) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.suggest.settings.ArraySettings.delete(ArraySettings.java:70) ~[fess-suggest-6.5.2.jar:?]
	at org.codelibs.fess.helper.SuggestHelper.init(SuggestHelper.java:105) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.7.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.7.jar:?]
	... 36 more

**Comment by marevol** [comment]
> 2019-05-29 09:33:30,365 [main] WARN Embedded Elasticsearch is running. This configuration is not recommended for production use.

You use Embedded Elasticsearch.
