### ISSUE TITLE
Web app 404's; logs show NoClassDefFoundError (after exhausting disk space)

### ISSUE THREAD

**Issue by festersearch** [codelibs/fess#2154]
My disk space ran out while fess was running. I have since cleaned things up (nothing to do with fess) and have plenty of disk space.

When I start fess, and try and visit the web app (either the main app, or the admin page).  I get 404 errors in the browser, and lots of "java.lang.NoClassDefFoundError: org/elasticsearch/index/IndexService$2" errors in the fess logs.

For example:
```

Exception in thread "elasticsearch[Node 1][management][T#5]" java.lang.NoClassDefFoundError: org/elasticsearch/index/IndexService$2
	at org.elasticsearch.index.IndexService.sync(IndexService.java:801)
	at org.elasticsearch.index.IndexService.syncRetentionLeases(IndexService.java:794)
	at org.elasticsearch.index.IndexService.access$800(IndexService.java:99)
	at org.elasticsearch.index.IndexService$AsyncRetentionLeaseSyncTask.runInternal(IndexService.java:975)
	at org.elasticsearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:141)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

```

**Comment by marevol** [comment]
Could you provide more information to reproduce it?
