### ISSUE TITLE
Can't load log handler "java.util.logging.FileHandler" in fess-12.4.3

### ISSUE THREAD

**Issue by MeMeLwin** [codelibs/fess#2165]
Although fess-12.4.3 perfectly works in 3 computers that I have installed.
In this 4th computer, when I run fess.bat, the following error occurs.

Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: C:fess-12.4.3\server_0.log.lck
java.nio.file.NoSuchFileException: C:fess-12.4.3\server_0.log.lck
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:116)
        at java.nio.channels.FileChannel.open(FileChannel.java:292)
        at java.nio.channels.FileChannel.open(FileChannel.java:340)
        at java.util.logging.FileHandler.openFiles(FileHandler.java:511)
        at java.util.logging.FileHandler.<init>(FileHandler.java:278)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by marevol** [comment]
> java.nio.file.NoSuchFileException: C:fess-12.4.3\server_0.log.lck

It's better to check your file system.
