### ISSUE TITLE
Warning in crawling 

### ISSUE THREAD

**Issue by UedaHideki** [codelibs/fess#2192]
Hi
use fess12.1.1

Warning happens in crawling.

2019-07-25 00:00:11,284 [Crawler-20190725000000-1-5] INFO  Crawling URL: smb://xxx..
2019-07-25 00:00:21,083 [IndexUpdater] INFO  Processing no docs (Doc:{access 4ms}, Mem:{used 302MB, heap 520MB, max 2GB})
2019-07-25 00:00:31,072 [IndexUpdater] INFO  Processing no docs (Doc:{access 1ms}, Mem:{used 302MB, heap 520MB, max 2GB})
2019-07-25 00:00:41,073 [IndexUpdater] INFO  Processing no docs (Doc:{access 2ms}, Mem:{used 302MB, heap 520MB, max 2GB})
2019-07-25 00:00:51,074 [IndexUpdater] INFO  Processing no docs (Doc:{access 2ms}, Mem:{used 304MB, heap 520MB, max 2GB})
2019-07-25 00:00:54,473 [Transport2] WARN  java.net.ConnectException: Connection timed out: connect
2019-07-25 00:00:54,474 [Transport2] WARN  	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
2019-07-25 00:00:54,474 [Transport2] WARN  	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
2019-07-25 00:00:54,474 [Transport2] WARN  	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
2019-07-25 00:00:54,474 [Transport2] WARN  	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
2019-07-25 00:00:54,474 [Transport2] WARN  	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
2019-07-25 00:00:54,474 [Transport2] WARN  	at java.net.PlainSocketImpl.connect(Unknown Source)
2019-07-25 00:00:54,475 [Transport2] WARN  	at java.net.SocksSocketImpl.connect(Unknown Source)
2019-07-25 00:00:54,475 [Transport2] WARN  	at java.net.Socket.connect(Unknown Source)
2019-07-25 00:00:54,475 [Transport2] WARN  	at jcifs.smb.SmbTransport.ssn139(SmbTransport.java:196)
2019-07-25 00:00:54,475 [Transport2] WARN  	at jcifs.smb.SmbTransport.negotiate(SmbTransport.java:249)
2019-07-25 00:00:54,475 [Transport2] WARN  	at jcifs.smb.SmbTransport.doConnect(SmbTransport.java:324)
2019-07-25 00:00:54,475 [Transport2] WARN  	at jcifs.util.transport.Transport.run(Transport.java:241)
2019-07-25 00:00:54,475 [Transport2] WARN  	at java.lang.Thread.run(Unknown Source)

Do you have any solution in this case?

**Comment by marevol** [comment]
Is it reproduced in the latest Fess?

**Comment by UedaHideki** [comment]
I can solve this problem.
File authentication setting:
from:
username: DOMAINNAME_ABBREBIATION\USERNAME
to:
username: USERNAME
pamameter: DOMAINNAME_FULL

>2019-07-25 00:00:54,473 [Transport2] WARN java.net.ConnectException: Connection timed out: connect

In "timed out", it occures that crawler try to access "DOMAINNAME_ABBREBIATION".
