### ISSUE TITLE
Crawler error

### ISSUE THREAD

**Issue by Anders-Bergqvist** [codelibs/fess#2226]
Crawler reports this in Fess_crawler.log. Why do I get this error?

```
2019-08-26 09:24:40,128 [Crawler-20190826000000-2-3] INFO  Crawling URL: https://www.oru.se/nyheter/nyhetsarkiv/nyhetsarkiv-2018/samarbete-i-klassrummet-motverkar-negativa-attityder-mot-invandrare/
2019-08-26 09:24:40,373 [Crawler-20190826000000-2-3] ERROR Crawling Exception at https://www.oru.se/nyheter/nyhetsarkiv/nyhetsarkiv-2018/samarbete-i-klassrummet-motverkar-negativa-attityder-mot-invandrare/
org.codelibs.fess.exception.ContainerNotAvailableException: fileTypeHelper is not available.
	at org.codelibs.fess.util.ComponentUtil.getComponent(ComponentUtil.java:464) ~[classes/:?]
	at org.codelibs.fess.util.ComponentUtil.getFileTypeHelper(ComponentUtil.java:310) ~[classes/:?]
	at org.codelibs.fess.crawler.transformer.FessXpathTransformer.putAdditionalData(FessXpathTransformer.java:359) ~[classes/:?]
	at org.codelibs.fess.crawler.transformer.FessXpathTransformer.storeData(FessXpathTransformer.java:188) ~[classes/:?]
	at org.codelibs.fess.crawler.transformer.impl.HtmlTransformer.transform(HtmlTransformer.java:120) ~[fess-crawler-3.1.0.jar:?]
	at org.codelibs.fess.crawler.processor.impl.DefaultResponseProcessor.process(DefaultResponseProcessor.java:77) ~[fess-crawler-3.1.0.jar:?]
	at org.codelibs.fess.crawler.CrawlerThread.processResponse(CrawlerThread.java:330) [fess-crawler-3.1.0.jar:?]
	at org.codelibs.fess.crawler.FessCrawlerThread.processResponse(FessCrawlerThread.java:240) ~[classes/:?]
	at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:176) [fess-crawler-3.1.0.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2019-08-26 09:24:40,773 [IndexUpdater] INFO  Processing 1/4 docs (Doc:{access 5ms}, Mem:{used 233MB, heap 512MB, max 512MB})
2019-08-26 09:24:40,774 [IndexUpdater] WARN  Failed to access data. Retry to access.. 1
org.codelibs.fess.exception.ContainerNotAvailableException: intervalControlHelper is not available.
	at org.codelibs.fess.util.ComponentUtil.getComponent(ComponentUtil.java:464) ~[classes/:?]
	at org.codelibs.fess.util.ComponentUtil.getIntervalControlHelper(ComponentUtil.java:298) ~[classes/:?]
	at org.codelibs.fess.indexer.IndexUpdater.getAccessResultList(IndexUpdater.java:509) ~[classes/:?]
	at org.codelibs.fess.indexer.IndexUpdater.run(IndexUpdater.java:230) [classes/:?]
2019-08-26 09:24:41,236 [Crawler-20190826000000-2-2] INFO  Crawling URL: https://www.oru.se/nyheter/nyhetsarkiv/nyhetsarkiv-2018/teori-och-praktik-for-skolledare-i-forsta-konferensen/
2019-08-26 09:24:41,520 [Crawler-20190826000000-2-2] ERROR Crawling Exception at https://www.oru.se/nyheter/nyhetsarkiv/nyhetsarkiv-2018/teori-och-praktik-for-skolledare-i-forsta-konferensen/
org.codelibs.fess.exception.ContainerNotAvailableException: fileTypeHelper is not available.
	at org.codelibs.fess.util.ComponentUtil.getComponent(ComponentUtil.java:464) ~[classes/:?]
	at org.codelibs.fess.util.ComponentUtil.getFileTypeHelper(ComponentUtil.java:310) ~[classes/:?]
	at org.codelibs.fess.crawler.transformer.FessXpathTransformer.putAdditionalData(FessXpathTransformer.java:359) ~[classes/:?]
	at org.codelibs.fess.crawler.transformer.FessXpathTransformer.storeData(FessXpathTransformer.java:188) ~[classes/:?]
	at org.codelibs.fess.crawler.transformer.impl.HtmlTransformer.transform(HtmlTransformer.java:120) ~[fess-crawler-3.1.0.jar:?]
	at org.codelibs.fess.crawler.processor.impl.DefaultResponseProcessor.process(DefaultResponseProcessor.java:77) ~[fess-crawler-3.1.0.jar:?]
	at org.codelibs.fess.crawler.CrawlerThread.processResponse(CrawlerThread.java:330) [fess-crawler-3.1.0.jar:?]
	at org.codelibs.fess.crawler.FessCrawlerThread.processResponse(FessCrawlerThread.java:240) ~[classes/:?]
	at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:176) [fess-crawler-3.1.0.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2019-08-26 09:24:44,624 [ShutdownHook] INFO  Disconnected to http://localhost:9200
2019-08-26 09:24:44,632 [ShutdownHook] INFO  Destroyed LaContainer.
```

**Comment by Anders-Bergqvist** [comment]
Fess 13.1.0
Elasticsearch 7.1.1

**Comment by marevol** [comment]
DI container seems to be stopped.
Could you provide the step to reproduce it?
