### ISSUE TITLE
error - PatternSyntaxException

### ISSUE THREAD

**Issue by rafael844** [codelibs/fess#2261]
Im getting this error: 
```
smb://10.200.51.134/setores/XXX/OPERACOES/XXXX - XXX-XXXX-000361-68 (XXX)/XXXX_XXXX/XXXX_2019-177_XXXX/Caso #0066, Transmissao #06609, em 26-11-2018, Analisada, XXXX XXXX XXXX/009-XXXXX-000361-68_INVEST.txt
Thread Name 	Crawler-20190929000000-1-5
Type 	java.util.regex.PatternSyntaxException
Log 	org.codelibs.fess.crawler.exception.CrawlingAccessException: Could not serialize object
at org.codelibs.fess.crawler.transformer.AbstractFessFileTransformer.transform(AbstractFessFileTransformer.java:83)
at org.codelibs.fess.crawler.processor.impl.DefaultResponseProcessor.process(DefaultResponseProcessor.java:77)
at org.codelibs.fess.crawler.CrawlerThread.processResponse(CrawlerThread.java:330)
at org.codelibs.fess.crawler.FessCrawlerThread.processResponse(FessCrawlerThread.java:240)
at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:176)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
.*\Thumb.db
   ^
at java.base/java.util.regex.Pattern.error(Pattern.java:2015)
at java.base/java.util.regex.Pattern.escape(Pattern.java:2604)
at java.base/java.util.regex.Pattern.atom(Pattern.java:2273)
at java.base/java.util.regex.Pattern.sequence(Pattern.java:2146)
at java.base/java.util.regex.Pattern.expr(Pattern.java:2056)
at java.base/java.util.regex.Pattern.compile(Pattern.java:1778)
at java.base/java.util.regex.Pattern.<init>(Pattern.java:1427)
at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
at org.codelibs.fess.es.config.exentity.FileConfig.initDocPathPattern(FileConfig.java:114)
at org.codelibs.fess.es.config.exentity.FileConfig.getIndexingTarget(FileConfig.java:65)
at org.codelibs.fess.crawler.transformer.AbstractFessFileTransformer.generateData(AbstractFessFileTransformer.java:185)
at org.codelibs.fess.crawler.transformer.AbstractFessFileTransformer.transform(AbstractFessFileTransformer.java:81)
... 5 more
```
It started after i put in  File Crawling Configuration :
Excluded Paths For Crawling: .*\thumb.db
.*\Thumb.db
.*\thumbs.db
.*\Thumbs.db
Excluded Paths For Indexing:
.*\thumb.db
.*\Thumb.db
.*\thumbs.db
.*\Thumbs.db

I didnt identify any \Thumb.db in this txt file that could cause this error. It is happenig with a lot of txt, pdf, xls files.

**Comment by marevol** [comment]
Try to replace `\` with `/`.

**Comment by rafael844** [comment]
that worked.
Should I do that with all the excluded paths?

```
.*/thumb.db
.*/Thumb.db
.*/thumbs.db
.*/Thumbs.db
.*\.class
.*\.css
.*\.ini
.*\.exe
.*\.dll
.*\.pyd
.*\.js
.*\.lnk
.*\.xry
.*\.iso
.*\.download
.*\.json
```

**Comment by marevol** [comment]
Yes. You need to replace it.

**Comment by rafael844** [comment]
thank you.
