### ISSUE TITLE
Failed to index from document in suggest processing

### ISSUE THREAD

**Issue by marevol** [codelibs/fess#2286]
```
2019-10-23 12:06:38,008 [pool-2-thread-1] ERROR Failed to update suggest index.
org.codelibs.fess.suggest.exception.SuggestIndexException: Failed to index from document
	at org.codelibs.fess.suggest.index.SuggestIndexer.indexFromDocument(SuggestIndexer.java:311) ~[fess-suggest-7.3.0.jar:?]
	at org.codelibs.fess.suggest.index.SuggestIndexer.lambda$indexFromDocument$11(SuggestIndexer.java:334) [fess-suggest-7.3.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_state_exception, reason=The number of tokens produced by calling _analyze has exceeded the allowed maximum of [10000]. This limit can be set by changing the [index.analyze.max_token_count] index level setting.]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.3.1.jar:7.3.1]
	at org.codelibs.elasticsearch.client.action.HttpAction.toElasticsearchException(HttpAction.java:138) ~[elasticsearch-httpclient-7.3.0.jar:?]
	at org.codelibs.elasticsearch.client.action.HttpAnalyzeAction.lambda$execute$0(HttpAnalyzeAction.java:67) ~[elasticsearch-httpclient-7.3.0.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:203) ~[curl4j-1.2.3.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:182) ~[curl4j-1.2.3.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
	Suppressed: org.elasticsearch.common.xcontent.XContentParseException: Failed to build [analyze_response] after last required field arrived
		at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.buildTarget(ConstructingObjectParser.java:476) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.finish(ConstructingObjectParser.java:457) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.access$000(ConstructingObjectParser.java:350) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:169) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
		at org.codelibs.elasticsearch.client.action.HttpAnalyzeAction.fromXContent(HttpAnalyzeAction.java:173) ~[elasticsearch-httpclient-7.3.0.jar:?]
		at org.codelibs.elasticsearch.client.action.HttpAnalyzeAction.lambda$execute$0(HttpAnalyzeAction.java:64) ~[elasticsearch-httpclient-7.3.0.jar:?]
		at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:203) ~[curl4j-1.2.3.jar:?]
		at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:182) ~[curl4j-1.2.3.jar:?]
		at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
	Caused by: java.lang.IllegalArgumentException: Neither token nor detail set on AnalysisAction.Response
		at org.elasticsearch.action.admin.indices.analyze.AnalyzeAction$Response.<init>(AnalyzeAction.java:297) ~[elasticsearch-7.3.1.jar:7.3.1]
		at org.codelibs.elasticsearch.client.action.HttpAnalyzeAction.lambda$static$6(HttpAnalyzeAction.java:166) ~[elasticsearch-httpclient-7.3.0.jar:?]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser.lambda$new$2(ConstructingObjectParser.java:132) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.buildTarget(ConstructingObjectParser.java:463) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
		... 13 more
	Suppressed: org.codelibs.elasticsearch.client.action.HttpAction$CurlResponseException: {"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[b0a43c2c71f1][172.18.0.3:9300][indices:admin/analyze[s]]"}],"type":"illegal_state_exception","reason":"The number of tokens produced by calling _analyze has exceeded the allowed maximum of [10000]. This limit can be set by changing the [index.analyze.max_token_count] index level setting."},"status":500}
```

**Comment by biligee** [comment]
It seems "Set document limit:50000" is not working?


 [pool-5-thread-1] INFO  Set document limitPercentage:50%
 [pool-5-thread-1] INFO  Set document limit:50000
 [pool-5-thread-1] WARN  Failed to parse document. Elasticsearch exception [type=illegal_state_exception, reason=The number of tokens produced by calling _analyze has exceeded the allowed maximum of [10000]. This limit can be set b
y changing the [index.analyze.max_token_count] index level setting.]
