### ISSUE TITLE
X-Pack Support for Fess could not be Installed

### ISSUE THREAD

**Issue by RickGER** [codelibs/fess#2412]
Hello guys, 
first thanks of all for interesting FESS Software. I want to use X-Pack Support for FESS and followed the instructions from [https://github.com/codelibs/fess-xpack](https://github.com/codelibs/fess-xpack)  to install it. 

1. The link of fess-xpack-12.6.0.0.jar, which you provided under Downloads on the GitHub Page [http://central.maven.org/maven2/org/codelibs/fess/fess-xpack/](http://central.maven.org/maven2/org/codelibs/fess/fess-xpack/) is down and doesnt work anymore. So I downloaded the .jar file from another page [https://mvnrepository.com/artifact/org.codelibs.fess/fess-xpack/12.6.0.0](https://mvnrepository.com/artifact/org.codelibs.fess/fess-xpack/12.6.0.0)

2. I followed exactly your instructions from the GitHub Explanation Page. Everything works fine, until I started the .jar File to download the missing dependicies. 

`java -Delasticsearch.version=6.7.2 -jar fess-xpack-12.6.0.0.jar`
It doesnt make a Difference if i wrote an other elasticsearchversion in the command e.g
`java -Delasticsearch.version=7.6.0 -jar fess-xpack-12.6.0.0.jar`

I received the following output: 
`Downloading from http://central.maven.org/maven2/com/vividsolutions/jts/1.13/jts-1.13.jar
java.net.UnknownHostException: central.maven.org
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:603)
	at java.base/java.net.Socket.connect(Socket.java:552)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.URL.openStream(URL.java:1163)
	at org.codelibs.fess.xpack.app.Install.download(Install.java:63)
	at org.codelibs.fess.xpack.app.Install.main(Install.java:45)`

It seems to look, that the maven repo where the software tries to download its dependicies is down. I tried it at different pc, it isnt an network issue.

Environment: 
Cent OS 8
Elasticsearch 7.6.0
Fess 13.6

By the way some other Links which are used in the source code of fess-xpack plugin seems also to be down.... [https://github.com/codelibs/fess-xpack/blob/master/src/main/java/org/codelibs/fess/xpack/app/Install.java](https://github.com/codelibs/fess-xpack/blob/master/src/main/java/org/codelibs/fess/xpack/app/Install.java)

I´am also not sure which downloads are really necessary. After all x-pack seems to be included after Elasticsearch Version 6.3 [https://www.elastic.co/what-is/open-x-pack](https://www.elastic.co/what-is/open-x-pack)

**Comment by RickGER** [comment]
By the way some other Links which are used in the source code of fess-xpack plugin seems also to be down.... [https://github.com/codelibs/fess-xpack/blob/master/src/main/java/org/codelibs/fess/xpack/app/Install.java](https://github.com/codelibs/fess-xpack/blob/master/src/main/java/org/codelibs/fess/xpack/app/Install.java)

**Comment by marevol** [comment]
It's not a bug.
fess-xpack does not support Fess 13.
