### ISSUE TITLE
特定のPDFのクロールでエラーが発生します

### ISSUE THREAD

**Issue by taizdo1024** [codelibs/fess#2441]
### 環境
WindowsServer2016上でfess-13.6.1を動作させています。

### 現象
ローカルファイルシステム上のPDFをクロールさせているのですが毎回以下のエラーが発生します。
試行錯誤をした結果、特定のPDFが存在すると発生しているように見えます。
見直すべき設定はどこかありますか。

### ログファイル
```
2020-04-01 20:55:43,237 [IndexUpdater] INFO  Processing 1/2 docs (Doc:{access 7ms}, Mem:{used 166MB, heap 434MB, max 512MB})
2020-04-01 20:55:43,357 [IndexUpdater] INFO  Processing 0/1 docs (Doc:{access 6ms, cleanup 113ms}, Mem:{used 167MB, heap 434MB, max 512MB})
2020-04-01 20:55:48,364 [IndexUpdater] INFO  Processing 1/1 docs (Doc:{access 7ms}, Mem:{used 168MB, heap 434MB, max 512MB})
2020-04-01 20:55:48,554 [IndexUpdater] INFO  Processing no docs in indexing queue (Doc:{access 4ms, cleanup 119ms}, Mem:{used 172MB, heap 434MB, max 512MB})
2020-04-01 20:55:48,783 [IndexUpdater] WARN  Failed to access data. Retry to access.. 1
org.codelibs.fess.es.client.FessEsClientException: failure in bulk execution:
[0]: index [fess.20200401], type [_doc], id [63615d7fae0f7ea127aab012dacc167c061f9b2c308b51f4a87a78056d9818ba87a12a2453f5d2148fbe7b1468acb16a886c8f589b1ca583d5b177b53be0640c], message [ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=7851,endOffset=7853,lastStartOffset=7852 for field 'content']]]
	at org.codelibs.fess.es.client.FessEsClient.addAll(FessEsClient.java:1018) ~[classes/:?]
	at org.codelibs.fess.helper.IndexingHelper.sendDocuments(IndexingHelper.java:74) ~[classes/:?]
	at org.codelibs.fess.indexer.IndexUpdater.run(IndexUpdater.java:227) [classes/:?]
```

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessJA/).
