### ISSUE TITLE
Failed File crawl after delete index

### ISSUE THREAD

**Issue by ji-ryoo** [codelibs/fess#2447]
FESS ver 13.4.5.1
elastic ver 7.4.2.1

After deleting the index file from the dashboard, running the default scheduler fails.

Expected behavior: Running the default scheduler to succeed

Workaround: I ran a restart of the fess process and it succeeded.

Below is the fess-crawl.log when it fails.

```
2020-04-23 16:13:07,662 [main] INFO  ...Loading specified properties and get by the key: fess_env_crawler.properties, lasta_di.smart.deploy.mode
2020-04-23 16:13:07,667 [main] INFO  ...Setting smart deploy mode: warm
2020-04-23 16:13:07,695 [main] INFO  ...Reading lasta_di.xml
2020-04-23 16:13:07,732 [main] INFO  ...Reading   redefiner.xml
2020-04-23 16:13:07,782 [main] INFO  ...Reading   smartdeploy.xml
2020-04-23 16:13:07,818 [main] INFO  ...Reading     smart/warmdeploy.xml
2020-04-23 16:13:07,823 [main] INFO  ...Reading       convention.xml
2020-04-23 16:13:07,827 [main] INFO  ...Reading         embedded_convention.xml
2020-04-23 16:13:07,839 [main] INFO  ...Reading       creator.xml
2020-04-23 16:13:07,843 [main] INFO  ...Reading         convention.xml (recycle)
2020-04-23 16:13:07,843 [main] INFO  ...Reading         customizer.xml
2020-04-23 16:13:07,847 [main] INFO  ...Reading           lastafw_customizer.xml
2020-04-23 16:13:07,857 [main] INFO  ...Reading           embedded_customizer.xml
2020-04-23 16:13:07,862 [main] INFO  ...Reading             tx_customizer.xml
2020-04-23 16:13:07,875 [main] INFO  ...Reading         my_creator.xml
2020-04-23 16:13:07,882 [main] INFO  ...Reading         lastafw_creator.xml
2020-04-23 16:13:07,886 [main] INFO  ...Reading           convention.xml (recycle)
2020-04-23 16:13:07,886 [main] INFO  ...Reading           customizer.xml (recycle)
2020-04-23 16:13:07,897 [main] INFO  ...Reading         embedded_creator.xml
2020-04-23 16:13:07,902 [main] INFO  ...Reading           convention.xml (recycle)
2020-04-23 16:13:07,902 [main] INFO  ...Reading           customizer.xml (recycle)
2020-04-23 16:13:07,908 [main] INFO  ...Reading       customizer.xml (recycle)
2020-04-23 16:13:07,931 [main] INFO  ...Reading app.xml
2020-04-23 16:13:07,936 [main] INFO  ...Reading   convention.xml
2020-04-23 16:13:07,940 [main] INFO  ...Reading     embedded_convention.xml
2020-04-23 16:13:07,949 [main] INFO  ...Reading   lastaflute_core.xml
2020-04-23 16:13:07,953 [main] INFO  ...Reading     lastaflute_assist.xml
2020-04-23 16:13:07,957 [main] INFO  ...Reading       lastaflute_director.xml
2020-04-23 16:13:08,056 [main] INFO  ...Reading   fess.xml
2020-04-23 16:13:08,059 [main] INFO  ...Reading     fess_config.xml
2020-04-23 16:13:08,066 [main] INFO  ...Reading     fess_ds.xml
2020-04-23 16:13:08,074 [main] INFO  ...Reading       jar:file:/usr/share/fess/app/WEB-INF/plugin/fess-ds-csv-13.4.0.jar!/fess_ds++.xml
2020-04-23 16:13:08,089 [main] INFO  ...Reading       jar:file:/usr/share/fess/app/WEB-INF/plugin/fess-ds-db-13.4.0.jar!/fess_ds++.xml
2020-04-23 16:13:08,095 [main] INFO  ...Reading     esflute_config.xml
2020-04-23 16:13:08,098 [main] INFO  ...Reading       esclient.xml
2020-04-23 16:13:08,292 [main] INFO  ...Reading     esflute_user.xml
2020-04-23 16:13:08,295 [main] INFO  ...Reading       esclient.xml (recycle)
2020-04-23 16:13:08,314 [main] INFO  ...Reading     esflute_log.xml
2020-04-23 16:13:08,317 [main] INFO  ...Reading       esclient.xml (recycle)
2020-04-23 16:13:09,539 [main] INFO  ...Reading   crawler_es.xml
2020-04-23 16:13:09,545 [main] INFO  ...Reading     crawler/container.xml
2020-04-23 16:13:09,550 [main] INFO  ...Reading     crawler/client.xml
2020-04-23 16:13:09,553 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,553 [main] INFO  ...Reading       crawler/robotstxt.xml
2020-04-23 16:13:09,556 [main] INFO  ...Reading         crawler/container.xml (recycle)
2020-04-23 16:13:09,560 [main] INFO  ...Reading       crawler/contentlength.xml
2020-04-23 16:13:09,562 [main] INFO  ...Reading         crawler/container.xml (recycle)
2020-04-23 16:13:09,563 [main] INFO  ...Reading       crawler/mimetype.xml
2020-04-23 16:13:09,566 [main] INFO  ...Reading         crawler/container.xml (recycle)
2020-04-23 16:13:09,640 [main] INFO  ...Reading     crawler/rule.xml
2020-04-23 16:13:09,644 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,644 [main] INFO  ...Reading       crawler/transformer.xml
2020-04-23 16:13:09,647 [main] INFO  ...Reading         crawler/transformer_basic.xml
2020-04-23 16:13:09,651 [main] INFO  ...Reading           crawler/container.xml (recycle)
2020-04-23 16:13:09,682 [main] INFO  ...Reading     crawler/filter.xml
2020-04-23 16:13:09,685 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,688 [main] INFO  ...Reading     crawler/interval.xml
2020-04-23 16:13:09,691 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,693 [main] INFO  ...Reading     crawler/extractor.xml
2020-04-23 16:13:09,696 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,708 [main] INFO  ...Reading       crawler/extractor+tikaExtractor.xml
2020-04-23 16:13:09,710 [main] INFO  ...Reading         crawler/container.xml
2020-04-23 16:13:09,752 [main] INFO  ...Reading     crawler/mimetype.xml (recycle)
2020-04-23 16:13:09,752 [main] INFO  ...Reading     crawler/encoding.xml
2020-04-23 16:13:09,755 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,756 [main] INFO  ...Reading     crawler/urlconverter.xml
2020-04-23 16:13:09,759 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,760 [main] INFO  ...Reading     crawler/log.xml
2020-04-23 16:13:09,763 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,766 [main] INFO  ...Reading     crawler/sitemaps.xml
2020-04-23 16:13:09,769 [main] INFO  ...Reading       crawler/container.xml (recycle)
2020-04-23 16:13:09,771 [main] INFO  ...Reading     crawler/es.xml
2020-04-23 16:13:09,784 [main] INFO  ...Reading     crawler_es+crawlerThread.xml
2020-04-23 16:13:09,803 [main] INFO  ...Reading     crawler_es+crawlerConfig.xml
2020-04-23 16:13:09,807 [main] INFO  ...Reading   fess_thumbnail.xml
2020-04-23 16:13:09,978 [main] INFO  [Objective Config]
2020-04-23 16:13:09,980 [main] INFO   fess_config.properties extends [fess_env_crawler.properties]
2020-04-23 16:13:09,980 [main] INFO   checkImplicitOverride=true, propertyCount=448
2020-04-23 16:13:10,023 [main] INFO  [Exception Translator]
2020-04-23 16:13:10,023 [main] INFO   exceptionTranslationProvider: null
2020-04-23 16:13:10,024 [main] INFO  [Async Manager]
2020-04-23 16:13:10,024 [main] INFO   defaultConcurrentAsyncOption: {no option}
2020-04-23 16:13:10,024 [main] INFO   primaryExecutorService: ThreadPoolExecutor@32f96bba
2020-04-23 16:13:10,024 [main] INFO   secondaryExecutorService: ThreadPoolExecutor@611640f0
2020-04-23 16:13:10,024 [main] INFO   tertiaryExecutorService: ThreadPoolExecutor@67e25252
2020-04-23 16:13:10,024 [main] INFO  [Primary Cipher]
2020-04-23 16:13:10,024 [main] INFO   invertibleCryptographer: {AES, UTF-8}
2020-04-23 16:13:10,024 [main] INFO   oneWayCryptographer: {SHA-256, UTF-8}
2020-04-23 16:13:10,026 [main] INFO  [Time Manager]
2020-04-23 16:13:10,026 [main] INFO   businessTimeHandler: TypicalBusinessTimeHandler:{TypicalTimeResourceProvider$$Lambda$117/0x000000084039c040, TypicalTimeResourceProvider$$Lambda$118/0x000000084039c440}
2020-04-23 16:13:10,026 [main] INFO   currentIgnoreTransaction: false
2020-04-23 16:13:10,026 [main] INFO   adjustTimeMillis: 0
2020-04-23 16:13:10,026 [main] INFO   adjustAbsoluteMode: false
2020-04-23 16:13:10,070 [main] INFO  [JSON Manager]
2020-04-23 16:13:10,071 [main] INFO   realJsonParser: GsonJsonEngine
2020-04-23 16:13:10,074 [main] INFO   mapping: {CAMEL_TO_LOWER_SNAKE}
2020-04-23 16:13:10,075 [main] INFO  [Postbox]
2020-04-23 16:13:10,075 [main] INFO   postOffice: PostOffice@65f40689
2020-04-23 16:13:10,075 [main] INFO   postalParkingLot: SMailPostalParkingLot:{{category:{main}=motorbike:{session=javax.mail.Session@29be997f}}}@33eb6758
2020-04-23 16:13:10,075 [main] INFO   postalPersonnel: FessMailDeliveryDepartmentCreator$1:{SMailConventionReceptionist:{[]}@f8a6243, batch:{[proofreader:{pmcomment}]}}@4a8ffd75
2020-04-23 16:13:10,386 [main] INFO  ConfigSync is ready.
2020-04-23 16:13:10,450 [main] INFO  Register mapping.txt to fess
2020-04-23 16:13:10,484 [main] INFO  Register synonym.txt to fess
2020-04-23 16:13:10,516 [main] INFO  Register ar/protwords.txt to fess
2020-04-23 16:13:10,551 [main] INFO  Register ca/protwords.txt to fess
2020-04-23 16:13:10,582 [main] INFO  Register ckb-iq/protwords.txt to fess
2020-04-23 16:13:10,615 [main] INFO  Register cs/protwords.txt to fess
2020-04-23 16:13:10,656 [main] INFO  Register da/protwords.txt to fess
2020-04-23 16:13:10,692 [main] INFO  Register de/protwords.txt to fess
2020-04-23 16:13:10,726 [main] INFO  Register el/protwords.txt to fess
2020-04-23 16:13:10,765 [main] INFO  Register en/protwords.txt to fess
2020-04-23 16:13:10,799 [main] INFO  Register en-ie/protwords.txt to fess
2020-04-23 16:13:10,834 [main] INFO  Register es/protwords.txt to fess
2020-04-23 16:13:10,866 [main] INFO  Register eu/protwords.txt to fess
2020-04-23 16:13:10,898 [main] INFO  Register fa/mapping.txt to fess
2020-04-23 16:13:10,936 [main] INFO  Register fa/protwords.txt to fess
2020-04-23 16:13:10,970 [main] INFO  Register fi/protwords.txt to fess
2020-04-23 16:13:11,006 [main] INFO  Register fr/protwords.txt to fess
2020-04-23 16:13:11,037 [main] INFO  Register gl/protwords.txt to fess
2020-04-23 16:13:11,072 [main] INFO  Register hi/protwords.txt to fess
2020-04-23 16:13:11,104 [main] INFO  Register hu/protwords.txt to fess
2020-04-23 16:13:11,138 [main] INFO  Register hy/protwords.txt to fess
2020-04-23 16:13:11,171 [main] INFO  Register id/protwords.txt to fess
2020-04-23 16:13:11,203 [main] INFO  Register it/protwords.txt to fess
2020-04-23 16:13:11,239 [main] INFO  Register ja/kuromoji.txt to fess
2020-04-23 16:13:11,274 [main] INFO  Register ja/mapping.txt to fess
2020-04-23 16:13:11,309 [main] INFO  Register ko/nori.txt to fess
2020-04-23 16:13:11,340 [main] INFO  Register lt/protwords.txt to fess
2020-04-23 16:13:11,370 [main] INFO  Register lv/protwords.txt to fess
2020-04-23 16:13:11,401 [main] INFO  Register nl/protwords.txt to fess
2020-04-23 16:13:11,432 [main] INFO  Register no/protwords.txt to fess
2020-04-23 16:13:11,509 [main] INFO  Register pt-br/protwords.txt to fess
2020-04-23 16:13:11,545 [main] INFO  Register pt/protwords.txt to fess
2020-04-23 16:13:11,585 [main] INFO  Register ro/protwords.txt to fess
2020-04-23 16:13:11,618 [main] INFO  Register ru/protwords.txt to fess
2020-04-23 16:13:11,657 [main] INFO  Register sv/protwords.txt to fess
2020-04-23 16:13:11,690 [main] INFO  Register th/protwords.txt to fess
2020-04-23 16:13:11,722 [main] INFO  Register tr/protwords.txt to fess
2020-04-23 16:13:11,762 [main] INFO  Register ar/stopwords.txt to fess
2020-04-23 16:13:11,805 [main] INFO  Register bg/stopwords.txt to fess
2020-04-23 16:13:11,840 [main] INFO  Register ca/stopwords.txt to fess
2020-04-23 16:13:11,875 [main] INFO  Register ckb-iq/stopwords.txt to fess
2020-04-23 16:13:11,906 [main] INFO  Register cs/stopwords.txt to fess
2020-04-23 16:13:11,943 [main] INFO  Register da/stopwords.txt to fess
2020-04-23 16:13:11,981 [main] INFO  Register de/stopwords.txt to fess
2020-04-23 16:13:12,016 [main] INFO  Register el/stopwords.txt to fess
2020-04-23 16:13:12,055 [main] INFO  Register en/stopwords.txt to fess
2020-04-23 16:13:12,089 [main] INFO  Register en-ie/stopwords.txt to fess
2020-04-23 16:13:12,127 [main] INFO  Register es/stopwords.txt to fess
2020-04-23 16:13:12,162 [main] INFO  Register eu/stopwords.txt to fess
2020-04-23 16:13:12,194 [main] INFO  Register fa/stopwords.txt to fess
2020-04-23 16:13:12,231 [main] INFO  Register fi/stopwords.txt to fess
2020-04-23 16:13:12,268 [main] INFO  Register fr/stopwords.txt to fess
2020-04-23 16:13:12,303 [main] INFO  Register gl/stopwords.txt to fess
2020-04-23 16:13:12,335 [main] INFO  Register hi/stopwords.txt to fess
2020-04-23 16:13:12,373 [main] INFO  Register hu/stopwords.txt to fess
2020-04-23 16:13:12,404 [main] INFO  Register hy/stopwords.txt to fess
2020-04-23 16:13:12,440 [main] INFO  Register id/stopwords.txt to fess
2020-04-23 16:13:12,478 [main] INFO  Register it/stopwords.txt to fess
2020-04-23 16:13:12,510 [main] INFO  Register ja/stopwords.txt to fess
2020-04-23 16:13:12,553 [main] INFO  Register ko/stopwords.txt to fess
2020-04-23 16:13:12,590 [main] INFO  Register lt/stopwords.txt to fess
2020-04-23 16:13:12,630 [main] INFO  Register lv/stopwords.txt to fess
2020-04-23 16:13:12,671 [main] INFO  Register nl/stopwords.txt to fess
2020-04-23 16:13:12,706 [main] INFO  Register no/stopwords.txt to fess
2020-04-23 16:13:12,742 [main] INFO  Register pt-br/stopwords.txt to fess
2020-04-23 16:13:12,777 [main] INFO  Register pt/stopwords.txt to fess
2020-04-23 16:13:12,810 [main] INFO  Register ro/stopwords.txt to fess
2020-04-23 16:13:12,848 [main] INFO  Register ru/stopwords.txt to fess
2020-04-23 16:13:12,891 [main] INFO  Register sv/stopwords.txt to fess
2020-04-23 16:13:12,928 [main] INFO  Register th/stopwords.txt to fess
2020-04-23 16:13:12,970 [main] INFO  Register tr/stopwords.txt to fess
2020-04-23 16:13:13,005 [main] INFO  Register vi/stopwords.txt to fess
2020-04-23 16:13:13,040 [main] INFO  Register zh-cn/stopwords.txt to fess
2020-04-23 16:13:13,074 [main] INFO  Register zh-tw/stopwords.txt to fess
2020-04-23 16:13:13,107 [main] INFO  Register ar/stemmer_override.txt to fess
2020-04-23 16:13:13,143 [main] INFO  Register bg/stemmer_override.txt to fess
2020-04-23 16:13:13,176 [main] INFO  Register ca/stemmer_override.txt to fess
2020-04-23 16:13:13,210 [main] INFO  Register ckb-iq/stemmer_override.txt to fess
2020-04-23 16:13:13,242 [main] INFO  Register cs/stemmer_override.txt to fess
2020-04-23 16:13:13,278 [main] INFO  Register da/stemmer_override.txt to fess
2020-04-23 16:13:13,309 [main] INFO  Register de/stemmer_override.txt to fess
2020-04-23 16:13:13,340 [main] INFO  Register el/stemmer_override.txt to fess
2020-04-23 16:13:13,370 [main] INFO  Register en/stemmer_override.txt to fess
2020-04-23 16:13:13,401 [main] INFO  Register en-ie/stemmer_override.txt to fess
2020-04-23 16:13:13,432 [main] INFO  Register es/stemmer_override.txt to fess
2020-04-23 16:13:13,464 [main] INFO  Register eu/stemmer_override.txt to fess
2020-04-23 16:13:13,494 [main] INFO  Register fi/stemmer_override.txt to fess
2020-04-23 16:13:13,524 [main] INFO  Register fr/stemmer_override.txt to fess
2020-04-23 16:13:13,559 [main] INFO  Register gl/stemmer_override.txt to fess
2020-04-23 16:13:13,593 [main] INFO  Register hi/stemmer_override.txt to fess
2020-04-23 16:13:13,621 [main] INFO  Register hu/stemmer_override.txt to fess
2020-04-23 16:13:13,658 [main] INFO  Register hy/stemmer_override.txt to fess
2020-04-23 16:13:13,686 [main] INFO  Register id/stemmer_override.txt to fess
2020-04-23 16:13:13,713 [main] INFO  Register it/stemmer_override.txt to fess
2020-04-23 16:13:13,745 [main] INFO  Register lt/stemmer_override.txt to fess
2020-04-23 16:13:13,777 [main] INFO  Register lv/stemmer_override.txt to fess
2020-04-23 16:13:13,809 [main] INFO  Register nl/stemmer_override.txt to fess
2020-04-23 16:13:13,842 [main] INFO  Register no/stemmer_override.txt to fess
2020-04-23 16:13:13,871 [main] INFO  Register pt-br/stemmer_override.txt to fess
2020-04-23 16:13:13,900 [main] INFO  Register pt/stemmer_override.txt to fess
2020-04-23 16:13:13,929 [main] INFO  Register ro/stemmer_override.txt to fess
2020-04-23 16:13:13,958 [main] INFO  Register ru/stemmer_override.txt to fess
2020-04-23 16:13:13,991 [main] INFO  Register sv/stemmer_override.txt to fess
2020-04-23 16:13:14,019 [main] INFO  Register tr/stemmer_override.txt to fess
2020-04-23 16:13:14,159 [main] INFO  Flushed config files.
2020-04-23 16:13:14,467 [main] WARN  fess_indices/fess.json is not found.
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=IOException while reading mappings_path: /etc/elasticsearch/ja/mapping.txt]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.codelibs.elasticsearch.client.action.HttpAction.toElasticsearchException(HttpAction.java:138) ~[elasticsearch-httpclient-7.4.1.jar:?]
	at org.codelibs.elasticsearch.client.action.HttpCreateIndexAction.lambda$execute$0(HttpCreateIndexAction.java:70) ~[elasticsearch-httpclient-7.4.1.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:220) ~[curl4j-1.2.4.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:199) ~[curl4j-1.2.4.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
	Suppressed: java.lang.IllegalArgumentException: Required [acknowledged, shards_acknowledged, index]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.finish(ConstructingObjectParser.java:446) ~[elasticsearch-x-content-7.4.2.jar:7.4.2]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.access$000(ConstructingObjectParser.java:350) ~[elasticsearch-x-content-7.4.2.jar:7.4.2]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:169) ~[elasticsearch-x-content-7.4.2.jar:7.4.2]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:161) ~[elasticsearch-x-content-7.4.2.jar:7.4.2]
		at org.elasticsearch.action.admin.indices.create.CreateIndexResponse.fromXContent(CreateIndexResponse.java:85) ~[elasticsearch-7.4.2.jar:7.4.2]
		at org.codelibs.elasticsearch.client.action.HttpCreateIndexAction.lambda$execute$0(HttpCreateIndexAction.java:67) ~[elasticsearch-httpclient-7.4.1.jar:?]
		at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:220) ~[curl4j-1.2.4.jar:?]
		at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:199) ~[curl4j-1.2.4.jar:?]
		at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
	Suppressed: org.codelibs.elasticsearch.client.action.HttpAction$CurlResponseException: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"IOException while reading mappings_path: /etc/elasticsearch/ja/mapping.txt"}],"type":"illegal_argument_exception","reason":"IOException while reading mappings_path: /etc/elasticsearch/ja/mapping.txt","caused_by":{"type":"no_such_file_exception","reason":"/etc/elasticsearch/ja/mapping.txt"}},"status":400}
Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=no_such_file_exception, reason=/etc/elasticsearch/ja/mapping.txt]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:491) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:432) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:598) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169) ~[elasticsearch-7.4.2.jar:7.4.2]
	... 10 more
2020-04-23 16:13:14,490 [main] WARN  fess_indices/fess/alias is not found.
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=index_not_found_exception, reason=no such index [fess.20200423]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.codelibs.elasticsearch.client.action.HttpAction.toElasticsearchException(HttpAction.java:138) ~[elasticsearch-httpclient-7.4.1.jar:?]
	at org.codelibs.elasticsearch.client.action.HttpIndicesAliasesAction.lambda$execute$0(HttpIndicesAliasesAction.java:71) ~[elasticsearch-httpclient-7.4.1.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:220) ~[curl4j-1.2.4.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:199) ~[curl4j-1.2.4.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
	Suppressed: java.lang.IllegalArgumentException: Required [acknowledged]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.finish(ConstructingObjectParser.java:446) ~[elasticsearch-x-content-7.4.2.jar:7.4.2]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.access$000(ConstructingObjectParser.java:350) ~[elasticsearch-x-content-7.4.2.jar:7.4.2]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:169) ~[elasticsearch-x-content-7.4.2.jar:7.4.2]
		at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:161) ~[elasticsearch-x-content-7.4.2.jar:7.4.2]
		at org.elasticsearch.action.support.master.AcknowledgedResponse.fromXContent(AcknowledgedResponse.java:104) ~[elasticsearch-7.4.2.jar:7.4.2]
		at org.codelibs.elasticsearch.client.action.HttpIndicesAliasesAction.lambda$execute$0(HttpIndicesAliasesAction.java:68) ~[elasticsearch-httpclient-7.4.1.jar:?]
		at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:220) ~[curl4j-1.2.4.jar:?]
		at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:199) ~[curl4j-1.2.4.jar:?]
		at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
	Suppressed: org.codelibs.elasticsearch.client.action.HttpAction$CurlResponseException: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [fess.20200423]","resource.type":"index_or_alias","resource.id":"fess.20200423","index_uuid":"_na_","index":"fess.20200423"}],"type":"index_not_found_exception","reason":"no such index [fess.20200423]","resource.type":"index_or_alias","resource.id":"fess.20200423","index_uuid":"_na_","index":"fess.20200423"},"status":404}
2020-04-23 16:13:14,502 [main] ERROR Crawler does not work correctly.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
esclient.xml

[Namespace]
null

[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml
* * * * * * * * * */
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.8.0.jar:?]
	at org.codelibs.fess.exec.Crawler.main(Crawler.java:221) [classes/:?]
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.FessEsClient, because [fess.20200423] IndexNotFoundException[no such index [fess.20200423]]
	at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.8.0.jar:?]
	at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.8.0.jar:?]
	... 8 more
Caused by: org.elasticsearch.index.IndexNotFoundException: no such index [fess.20200423]
	at org.codelibs.elasticsearch.client.action.HttpGetMappingsAction.lambda$execute$0(HttpGetMappingsAction.java:47) ~[elasticsearch-httpclient-7.4.1.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$execute$4(CurlRequest.java:220) ~[curl4j-1.2.4.jar:?]
	at org.codelibs.curl.CurlRequest.lambda$connect$3(CurlRequest.java:199) ~[curl4j-1.2.4.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1op020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
2020-04-23 16:13:14,507 [main] INFO  Destroyed LaContainer.
```
Do you know the cause?

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).
