### ISSUE TITLE
FESS 404 "Not found the webapp directory" in Windows Install

### ISSUE THREAD

**Issue by joemammy47** [codelibs/fess#2472]
We're having issues getting the latest version of FESS working on a Windows Install.
Elastic: 7.8.0
FESS: 13.8.1
AdoptOpenJDK: Currently 11 HotSpot, have also tried 11 OpenJ, and 14 HotSpot and OpenJ

Elastic service and fess service both install fine, but FESS is not working. The service will start, but the localhost:8080 returns a 404. This is from the stderr log from FESS:

2020-07-24 09:09:48 Commons Daemon procrun stderr initialized
java.lang.IllegalStateException: Not found the webapp directory: .\src\main\webapp
                at org.dbflute.tomcat.TomcatBoot.deriveWebappDir(TomcatBoot.java:568)
                at org.dbflute.tomcat.TomcatBoot.prepareWebappPath(TomcatBoot.java:551)
                at org.codelibs.fess.FessBoot.prepareWebappPath(FessBoot.java:54)
                at org.dbflute.tomcat.TomcatBoot.doSetupWebappContextWebappDir(TomcatBoot.java:447)
                at org.dbflute.tomcat.TomcatBoot.setupWebappContext(TomcatBoot.java:432)
                at org.dbflute.tomcat.TomcatBoot.prepareServer(TomcatBoot.java:416)
                at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:401)
                at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:347)
                at org.codelibs.fess.FessBoot.main(FessBoot.java:94)

**Comment by marevol** [comment]
Please use [discuss.codelibs.org](https://discuss.codelibs.org/c/FessEN/).
