### ISSUE TITLE
Error occured in starting fess service (A JNI error)

### ISSUE THREAD

**Issue by NikaidoKota** [codelibs/fess#2652]
Hello.

I installed fess and elasticsearch on the AWS EC2 server (Amazon Linux).
When starting fess service for the first time, it failed to start with the following error.
```
$ sudo systemctl status fess.service
● fess.service - Fess
   Loaded: loaded (/usr/lib/systemd/system/fess.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2022-05-19 05:27:05 UTC; 6s ago
     Docs: http://fess.codelibs.org/
  Process: 1372 ExecStart=/usr/share/fess/bin/fess (code=exited, status=1/FAILURE)
 Main PID: 1372 (code=exited, status=1/FAILURE)
```

```
fess[1372]: Error: A JNI error has occurred, please check your installation and try again
fess[1372]: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/codelibs/fess/FessBoot has been
fess[1372]: at java.lang.ClassLoader.defineClass1(Native Method)
fess[1372]: at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
fess[1372]: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
fess[1372]: at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
fess[1372]: at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
fess[1372]: at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
fess[1372]: at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
fess[1372]: at java.security.AccessController.doPrivileged(Native Method)
fess[1372]: at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
fess[1372]: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
fess[1372]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
fess[1372]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
fess[1372]: at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
systemd[1]: fess.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit fess.service entered failed state.
systemd[1]: fess.service failed.
```

The java version is as follows.
```
$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

```
$ alternatives --config java
  Selection    Command
-----------------------------------------------
*+ 1           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-1.amzn2.0.2.x86_64/jre/bin/java)
```

The version of the fess rpm packages is as follows.
```
$ rpm -qi fess
Name        : fess
Version     : 14.1.0
Release     : 1
Architecture: noarch
Install Date: Thu 19 May 2022 05:26:54 AM UTC
Group       : Application/Internet
Size        : 201909421
License     : (c) 2009 CodeLibs
Signature   : (none)
Source RPM  : fess-14.1.0-1.src.rpm
Build Date  : Sun 24 Apr 2022 12:03:54 PM UTC
Build Host  : sanjose
Relocations : /usr
Packager    : CodeLibs
Vendor      : CodeLibs
URL         : https://fess.codelibs.org/
Summary     : Fess
Description :
Fess is Full tExt Search System.
```

elasticsearch is running fine.

It looks like there is a problem with the Java version, can you please let me know how to solve it?

**Comment by marevol** [comment]
Please see [Installation Guide](https://fess.codelibs.org/14.1/install/install.html#requirements).
