### ISSUE TITLE
Can't load log handler on Windows 10

### ISSUE THREAD

**Issue by kitakita** [codelibs/fess#347]
FESS: 10.0.0 rc1
OS: Windows 10
Java: JDK8u66

File handler escape '\' in FESS_HOME.
Look This.

```
C:\work\fess-10.0.0-rc1\bin>fess.bat
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: C:workfess-10.0.0-rc1logs\server_0.log.lck
java.nio.file.NoSuchFileException: C:workfess-10.0.0-rc1logs\server_0.log.lck
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
        at java.util.logging.FileHandler.<init>(FileHandler.java:263)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.logging.LogManager$5.run(LogManager.java:966)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
        at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
        at java.util.logging.LogManager.access$1500(LogManager.java:145)
        at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
        at java.util.logging.Logger.getHandlers(Logger.java:1776)
        at java.util.logging.Logger.log(Logger.java:735)
        at java.util.logging.Logger.doLog(Logger.java:765)
        at java.util.logging.Logger.log(Logger.java:788)
        at java.util.logging.Logger.info(Logger.java:1489)
        at org.dbflute.tomcat.TomcatBoot.info(TomcatBoot.java:662)
        at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:228)
        at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:183)
        at org.codelibs.fess.FessBoot.main(FessBoot.java:87)
```

英語がアレなので、以下日本語です。
上記エラーは出るものの起動自体はされていて、Web画面にもアクセスできますが server_0.log と server_0.log.lck が書き出されませんでした。fess.log, audit.log, mail.log は書き出されています。

原因を推測してみましたが、このログのファイルハンドラだけ sun.nio.fs.WindowsPathParser を介しているみたいなので※これが '\' をエスケープしてしまっているのでは無いかと思います。

※ `fess.in.bat` の `-Dfess.log.path=%FESS_HOME%\logs` を `-Dfess.log.path='%FESS_HOME%'\logs` に変えると以下のエラーが出るため。

```
C:\work\fess-10.0.0-rc1\bin>fess.bat
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.InvalidPathException: Illegal char <:> at index 2: 'C:workfess-10.0.0-rc1logs'\server_0.log.lck
java.nio.file.InvalidPathException: Illegal char <:> at index 2: 'C:workfess-10.0.0-rc1logs'\server_0.log.lck
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at java.util.logging.FileHandler.openFiles(FileHandler.java:453)
        at java.util.logging.FileHandler.<init>(FileHandler.java:263)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.logging.LogManager$5.run(LogManager.java:966)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
        at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
        at java.util.logging.LogManager.access$1500(LogManager.java:145)
        at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
        at java.util.logging.Logger.getHandlers(Logger.java:1776)
        at java.util.logging.Logger.log(Logger.java:735)
        at java.util.logging.Logger.doLog(Logger.java:765)
        at java.util.logging.Logger.log(Logger.java:788)
        at java.util.logging.Logger.info(Logger.java:1489)
        at org.dbflute.tomcat.TomcatBoot.info(TomcatBoot.java:662)
        at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:228)
        at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:183)
        at org.codelibs.fess.FessBoot.main(FessBoot.java:87)
以下略
```

**Comment by marevol** [comment]
It will be fixed in GA release.
