### ISSUE TITLE
Change indexer.webfs.max.empty.list.count to 360

### ISSUE THREAD

**Issue by marevol** [codelibs/fess#450]
- change to 360(1 hour)
- fix typo

**Comment by stweil** [comment]
When indexing a [large directory](https://digi.bib.uni-mannheim.de/periodika/reichsanzeiger/ocr/film/tesseract-4.0.0-alpha.20170703/), my indexer aborts without having indexed any document even with `360`:

    2017-08-03 01:00:36,597 [IndexUpdater] INFO  Terminating indexUpdater. emptyListCount is over 360.
    2017-08-03 01:00:36,631 [IndexUpdater] INFO  Thread: Thread[elasticsearch[_client_][transport_client_boss][T#15],5,main]
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:752)
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    2017-08-03 01:00:36,632 [IndexUpdater] INFO     at java.lang.Thread.run(Thread.java:748)
[...]

Is this normal?
Should I increase `indexer.webfs.max.empty.list.count` in `/etc/fess/fess_config.properties`,
or is there a better solution?
Currently I can only index small numbers of subdirectories (which works).

**Comment by marevol** [comment]
> Is this normal?

 emptyListCount is like circuit breaker to avoid unknown crawling problems. 

> Should I increase indexer.webfs.max.empty.list.count in /etc/fess/fess_config.properties

Yes. If you have a lot of not-updated files, you need to increase it.

**Comment by stweil** [comment]
Thank you. Increasing the value from 360 to 720 fixed my broken indexing.

**Comment by stweil** [comment]
I was mistaken – the change to 720 only temporarily helped. The indexing process terminated this morning after having indexed more than 360000 documents. It then started again looking at the directories, exceeded the 720 limit and raised an exception again. Even worse: while I had a search index with more than 300000 entries yesterday evening (after several days of crawling), the search index is now at 0 entries again. :-(

It looks like Fess does not like large directory structures where only the files but not the directories are indexed.

**Comment by marevol** [comment]
In our commercial support, Fess provides crawling/indexing over 10,000,000 documents for enterprise search.
However, to support a large file system, you need a lot of knowledge for Fess and elasticsearch.
So, proper settings and server design are needed.
emptyListCount is one of parameters. If you use File System crawling, you should increase it more. For a large file system, we recommend to use [CsvListDataStore](http://fess.codelibs.org/11.2/admin/dataconfig-guide.html).

> the search index is now at 0 entries again.

See [Remove Documents Before](http://fess.codelibs.org/11.2/admin/general-guide.html#remove-documents-before).

**Comment by stweil** [comment]
I already had noticed `Remove Documents Before` before and increased it to 300 days.
And I use Web crawling (URL https://digi.bib.uni-mannheim.de/periodika/reichsanzeiger/ocr/film/tesseract-4.0.0-alpha.20170703/). For the new crawling, I'll try `indexer.webfs.max.empty.list.count` set to 3600.
