### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#629]
Hi, I am just getting started with this. I was unable to install the dependencies for the project. 

`mvn antrun:run -X`

Looks like this file might not be accessible:
Downloading: http://maven.codelibs.org/org/sonatype/oss/oss-parent/9/oss-parent-9.pom

		  [ERROR] The build could not read 1 project -> [Help 1]
			org.apache.maven.project.ProjectBuildingException: Some problems were encountered while            processing the POMs:
		[FATAL] Non-resolvable parent POM for org.codelibs.fess:fess:10.2.0-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:9 from/to codelibs.org (http://maven.codelibs.org/): Connect to maven.codelibs.org:80 [maven.codelibs.org/49.212.198.183] failed: Connection timed out: connect and 'parent.relativePath' points at wrong local POM @ line 31, column 10

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
		[ERROR]
		[ERROR]   The project org.codelibs.fess:fess:10.2.0-SNAPSHOT (C:\Users\atti\Projects\fess\pom.xml) has 1 error
		[ERROR]     Non-resolvable parent POM for org.codelibs.fess:fess:10.2.0-SNAPSHOT: Could not transfer artifact org.sonatype.oss:oss-parent:pom:9 from/to codelibs.org (http://maven.codelibs.org/): Connect to maven.codelibs.org:80 [maven.codelibs.org/49.212.198.183] failed: Connection timed out: connect and 'parent.relativePath' points at wrong local POM @ line 31,

**Comment by marevol** [comment]
> Connect to maven.codelibs.org:80 [maven.codelibs.org/49.212.198.183] failed: Connection timed out

I think it's a network problem.
Could you check if your mvn connects to maven.codelibs.org?

**Comment by attibalazs** [comment]
hi, thanks for the quick answer and for putting together a great solution.
You are right it was a connection problem, i am behind a proxy. 

This article helped:
http://stackoverflow.com/questions/16729023/maven-build-issue-connection-to-repository-refused
