### ISSUE TITLE
Error when running mvn antrun:run

### ISSUE THREAD

**Issue by attibalazs** [codelibs/fess#664]
Hi, i started again on a new machine.
When i try to do mvn antrun:run i get the following error. Looks like it doesn`t have access to the URL to download the dependencies for the crawler.

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 5.138 s
> [INFO] Finished at: 2016-09-02T09:22:49+01:00
> [INFO] Final Memory: 23M/228M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project fess: Could not resolve dependencies for project org.codelibs.fess:fess:war:11.0.0-SNAPSHOT: Failed to collect dependencies at org.codelibs.fess:fess-crawler-lasta:jar:1.0.10 -> org.codelibs.fess:fess-crawler:jar:1.0.10 -> jp.gr.java_conf.dangan:jlha:jar:0.06-05: Failed to read artifact descriptor for jp.gr.java_conf.dangan:jlha:jar:0.06-05: Could not transfer artifact jp.gr.java_conf.dangan:jlha:pom:0.06-05 from/to codelibs.org (http://maven.codelibs.org/): Access denied to: http://maven.codelibs.org/jp/gr/java_conf/dangan/jlha/0.06-05/jlha-0.06-05.pom , ReasonPhrase:Forbidden. -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project fess: Could not resolve dependencies for project org.codelibs.fess:fess:war:11.0.0-SNAPSHOT: Failed to collect dependencies at org.codelibs.fess:fess-crawler-lasta:jar:1.0.10 -> org.codelibs.fess:fess-crawler:jar:1.0.10 -> jp.gr.java_conf.dangan:jlha:jar:0.06-05
> 	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
> 	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.codelibs.fess:fess:war:11.0.0-SNAPSHOT: Failed to collect dependencies at org.codelibs.fess:fess-crawler-lasta:jar:1.0.10 -> org.codelibs.fess:fess-crawler:jar:1.0.10 -> jp.gr.java_conf.dangan:jlha:jar:0.06-05
> 	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
> 	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
> 	... 23 more
> Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.codelibs.fess:fess-crawler-lasta:jar:1.0.10 -> org.codelibs.fess:fess-crawler:jar:1.0.10 -> jp.gr.java_conf.dangan:jlha:jar:0.06-05
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
> 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
> 	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
> 	... 24 more
> Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for jp.gr.java_conf.dangan:jlha:jar:0.06-05
> 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
> 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
> 	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
> 	... 26 more
> Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact jp.gr.java_conf.dangan:jlha:pom:0.06-05 from/to codelibs.org (http://maven.codelibs.org/): Access denied to: http://maven.codelibs.org/jp/gr/java_conf/dangan/jlha/0.06-05/jlha-0.06-05.pom , ReasonPhrase:Forbidden.
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
> 	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
> 	... 41 more
> Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact jp.gr.java_conf.dangan:jlha:pom:0.06-05 from/to codelibs.org (http://maven.codelibs.org/): Access denied to: http://maven.codelibs.org/jp/gr/java_conf/dangan/jlha/0.06-05/jlha-0.06-05.pom , ReasonPhrase:Forbidden.
> 	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
> 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
> 	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
> 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
> 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
> 	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
> 	... 44 more
> Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Access denied to: http://maven.codelibs.org/jp/gr/java_conf/dangan/jlha/0.06-05/jlha-0.06-05.pom , ReasonPhrase:Forbidden.
> 	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1001)
> 	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
> 	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
> 	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
> 	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
> 	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
> 	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
> 	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
> 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
> 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
> 	... 49 more
> [ERROR] 
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
>

**Comment by attibalazs** [comment]
Nevermind, it looks like your domain was being blocked by the corporate proxy. I am trying it with a different connection and it`s working.
