### ISSUE TITLE
Running Fess as service

### ISSUE THREAD

**Issue by TuminD** [codelibs/fess#717]
Hi

I tried to install fess to run as service in windows server 2012 R2 - 
I ran "service.bat install" and got message:
"The service 'fess-service-x64' has been installed"
I started this win service, but couldn't connect to web interface (http://localhost:8080)

But if i start fess by running "fess.bat" it works ok and i can connect to web UI

Is it possible to run fess as a service?

**Comment by marevol** [comment]
Could you check log files in logs folder?

**Comment by TuminD** [comment]
In fess-service-x64.YYYY-MM-DD.log:

[2016-09-30 10:35:23] [info]  [ 6380] Commons Daemon procrun (1.0.15.0 64-bit) started
[2016-09-30 10:35:23] [info]  [ 6380] Starting service 'fess-service-x64' ...
[2016-09-30 10:35:23] [info]  [ 7580] Commons Daemon procrun (1.0.15.0 64-bit) started
[2016-09-30 10:35:23] [info]  [ 7580] Running 'fess-service-x64' Service...
[2016-09-30 10:35:23] [info]  [ 6376] Starting service...
[2016-09-30 10:35:24] [info]  [ 6376] Service started in 1209 ms.
[2016-09-30 10:35:26] [info]  [ 6380] Service 'fess-service-x64' started
[2016-09-30 10:35:26] [info]  [ 6380] Start service finished.
[2016-09-30 10:35:26] [info]  [ 6380] Commons Daemon procrun finished

In fess-service-x64-stderr.YYYY-MM-DD.log there are:

java.lang.IllegalStateException: **Not found the webapp directory**: .\src\main\webapp
	at org.dbflute.tomcat.TomcatBoot.deriveWebappDir(TomcatBoot.java:356)
	at org.dbflute.tomcat.TomcatBoot.prepareWebappPath(TomcatBoot.java:339)
	at org.codelibs.fess.FessBoot.prepareWebappPath(FessBoot.java:51)
	at org.dbflute.tomcat.TomcatBoot.setupWebappContext(TomcatBoot.java:270)
	at org.dbflute.tomcat.TomcatBoot.prepareServer(TomcatBoot.java:251)
	at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:236)
	at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:183)
	at org.codelibs.fess.FessBoot.main(FessBoot.java:87)

Is it cause ? How to resolve it ?

[fess-service-x64-stderr.2016-09-30.zip](https://github.com/codelibs/fess/files/502356/fess-service-x64-stderr.2016-09-30.zip)

**Comment by marevol** [comment]
Hmm, the following line in service.bat may not work in your environment...

    set FESS_PARAMS=-Dfess;-Dfess.home="%FESS_HOME%";-Dfess.es.dir="%ES_HOME%";-Dfess.home="%FESS_HOME%";-Dfess.context.path="/";-Dfess.port=8080;-Dfess.webapp.path="%FESS_HOME%\app";-Dfess.temp.path="%FESS_HOME%\temp";-Dfess.log.name="%APP_NAME%";-Dfess.log.path="%FESS_HOME%\logs";-Dfess.log.level=warn;-Dlasta.env=web;-Dtomcat.config.path=tomcat_config.properties

**Comment by TuminD** [comment]
But it doesn't give any error during service installation.

Also i installed standalone Elasticsearch service on the same server - and it works fine (as i understand elastic has similar installation scheme and service.bat file)

**Comment by TuminD** [comment]
Can you give any guesses why "set FESS_PARAMS" doesn't work in Windows server 2012 R2 environment?

**Comment by TuminD** [comment]
Any ideas?

**Comment by marevol** [comment]
Sorry for the late response.
Fixed in Fess 10.2.2.
