### ISSUE TITLE
OOM on generateThumbnailJob

### ISSUE THREAD

**Issue by marevol** [codelibs/fess#776]
```
2016-11-07 10:40:53,286 [job_thumbnail_generate] ERROR Failed to execute thumbnail_generate: return container.getComponent("generateThumbnailJob").execute();
java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:92)
        at java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:445)
        at java.awt.image.Raster.createWritableRaster(Raster.java:941)
        at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1074)
        at javax.imageio.ImageReader.getDestination(ImageReader.java:2892)
        at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1309)
        at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1606)
        at javax.imageio.ImageIO.read(ImageIO.java:1448)
        at javax.imageio.ImageIO.read(ImageIO.java:1352)
        at org.codelibs.fess.thumbnail.impl.WebDriverGenerator.loadImage(WebDriverGenerator.java:185)
        at org.codelibs.fess.thumbnail.impl.WebDriverGenerator.convert(WebDriverGenerator.java:170)
        at org.codelibs.fess.thumbnail.impl.WebDriverGenerator.generate(WebDriverGenerator.java:140)
        at org.codelibs.fess.thumbnail.ThumbnailManager.lambda$generate$1028(ThumbnailManager.java:209)
        at org.codelibs.fess.thumbnail.ThumbnailManager$$Lambda$444/1287692070.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.codelibs.fess.thumbnail.ThumbnailManager.generate(ThumbnailManager.java:198)
        at org.codelibs.fess.job.GenerateThumbnailJob.execute(GenerateThumbnailJob.java:30)
        at org.codelibs.fess.job.GenerateThumbnailJob$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at Script1.run(Script1.groovy:1)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
        at org.codelibs.fess.util.GroovyUtil.evaluate(GroovyUtil.java:41)
        at org.codelibs.fess.job.impl.GroovyExecutor.execute(GroovyExecutor.java:31)
        at org.codelibs.fess.app.job.ScriptExecutorJob.run(ScriptExecutorJob.java:91)
        at org.lastaflute.job.LaJobRunner.actuallyRun(LaJobRunner.java:169)
        at org.lastaflute.job.LaJobRunner.doRun(LaJobRunner.java:154)
        at org.lastaflute.job.LaJobRunner.run(LaJobRunner.java:110)
        at org.lastaflute.job.cron4j.Cron4jTask.runJob(Cron4jTask.java:150)
```

**Comment by marevol** [comment]
```
2016-11-09 23:24:29,042 [job_thumbnail_generate] WARN  Failed to convert /var/tmp/fess/screenshot5470922246855855401.png
java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:92)
        at java.awt.image.ComponentSampleModel.createDataBuffer(ComponentSampleModel.java:445)
        at java.awt.image.Raster.createWritableRaster(Raster.java:941)
        at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1074)
        at javax.imageio.ImageReader.getDestination(ImageReader.java:2892)
        at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1309)
        at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1606)
        at javax.imageio.ImageIO.read(ImageIO.java:1448)
        at javax.imageio.ImageIO.read(ImageIO.java:1352)
        at org.codelibs.fess.thumbnail.impl.WebDriverGenerator.loadImage(WebDriverGenerator.java:191)
        at org.codelibs.fess.thumbnail.impl.WebDriverGenerator.convert(WebDriverGenerator.java:171)
        at org.codelibs.fess.thumbnail.impl.WebDriverGenerator.generate(WebDriverGenerator.java:141)
        at org.codelibs.fess.thumbnail.ThumbnailManager.lambda$generate$1028(ThumbnailManager.java:209)
        at org.codelibs.fess.thumbnail.ThumbnailManager$$Lambda$503/741125423.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.codelibs.fess.thumbnail.ThumbnailManager.generate(ThumbnailManager.java:198)
        at org.codelibs.fess.job.GenerateThumbnailJob.execute(GenerateThumbnailJob.java:30)
        at org.codelibs.fess.job.GenerateThumbnailJob$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at Script1.run(Script1.groovy:1)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:594)
        at org.codelibs.fess.util.GroovyUtil.evaluate(GroovyUtil.java:41)
        at org.codelibs.fess.job.impl.GroovyExecutor.execute(GroovyExecutor.java:31)
        at org.codelibs.fess.app.job.ScriptExecutorJob.run(ScriptExecutorJob.java:91)
        at org.lastaflute.job.LaJobRunner.actuallyRun(LaJobRunner.java:169)
        at org.lastaflute.job.LaJobRunner.doRun(LaJobRunner.java:154)
        at org.lastaflute.job.LaJobRunner.run(LaJobRunner.java:110)
        at org.lastaflute.job.cron4j.Cron4jTask.runJob(Cron4jTask.java:150)
```
