### ISSUE TITLE
Java heap space

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#788]
com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: Java heap space

how fix

**Comment by marevol** [comment]
Could you provide all stack traces?

**Comment by MajidSafari** [comment]
2016-11-17 06:22:22,683 [Crawler-AVhfp0YAsf_z_dCmnTkH-1-9] ERROR Crawling Exception at http://www.kanoon.ir/Amoozesh/Video/21-1-40888-1
java.lang.OutOfMemoryError: Java heap space
	at org.apache.commons.io.output.ByteArrayOutputStream.needNewBuffer(ByteArrayOutputStream.java:127)
	at org.apache.commons.io.output.ByteArrayOutputStream.write(ByteArrayOutputStream.java:158)
	at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:129)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at org.codelibs.core.io.CopyUtil.copyInternal(CopyUtil.java:1297)
	at org.codelibs.core.io.CopyUtil.copy(CopyUtil.java:152)
	at org.codelibs.fess.crawler.client.http.HcHttpClient.processHttpMethod(HcHttpClient.java:656)
	at org.codelibs.fess.crawler.client.http.HcHttpClient.doHttpMethod(HcHttpClient.java:573)
	at org.codelibs.fess.crawler.client.http.HcHttpClient.doGet(HcHttpClient.java:532)
	at org.codelibs.fess.crawler.client.AbstractCrawlerClient.execute(AbstractCrawlerClient.java:135)
	at org.codelibs.fess.crawler.client.FaultTolerantClient.execute(FaultTolerantClient.java:67)
	at org.codelibs.fess.crawler.CrawlerThread.run(CrawlerThread.java:164)
	at java.lang.Thread.run(Thread.java:745)

**Comment by marevol** [comment]
I think that it's just a Java Heap memory shortage.
It depends on crawler settings.
Please change -Xmx value in fess_config.properties.

```
jvm.crawler.options=\
-Djava.awt.headless=true\n\
-server\n\
-Xmx512m\n\ <-- ex. change to -Xmx1g\n\ 
```
