### ISSUE TITLE
Mapper for requestedAt conflicts with existing mapping

### ISSUE THREAD

**Issue by MajidSafari** [codelibs/fess#822]
2016-12-19 17:20:19,752 [main] INFO  [Postbox]
2016-12-19 17:20:19,752 [main] INFO   postOffice: PostOffice@293bb8a5
2016-12-19 17:20:19,752 [main] INFO   postalParkingLot: SMailPostalParkingLot:{{category:{main}=motorbike:{session=javax.mail.Session@2416a51}}}@6fa590ba
2016-12-19 17:20:19,752 [main] INFO   postalPersonnel: FessMailDeliveryDepartmentCreator$1:{SMailConventionReceptionist:{[]}@6e9319f, batch:{[proofreader:{pmcomment}]}}@72e34f77
2016-12-19 17:20:20,707 [main] INFO  [Sean Cassidy] modules [], plugins [], sites []
2016-12-19 17:20:22,848 [main] WARN  Failed to create fess_log/click_log mapping.
java.lang.IllegalArgumentException: Mapper for [requestedAt] conflicts with existing mapping in other types:
[mapper [requestedAt] is used by multiple types. Set update_all_types to true to update [format] across all types.]
	at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:153)
	at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:115)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:381)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:320)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:306)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:480)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:784)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by marevol** [comment]
Did you change mappings? Could you provide steps to reproduce it?

**Comment by MajidSafari** [comment]
don't change mappings

**Comment by MajidSafari** [comment]
how to fix ? or check ?

**Comment by marevol** [comment]
Need more info to reproduce it.
