### ISSUE TITLE
:8080 inaccessible after install

### ISSUE THREAD

**Issue by IanRarity** [codelibs/fess#912]
New server (OpenSuse Leap 42.1), with ElasticSearch 5.2.0 (installed from OS repo) and Fess 11.0 (installed from fess.codelibs.org).  I followed the installation guide at http://fess.codelibs.org/11.0/install/index.html and have a working ES instance that I can talk to on port 9200.

Fess doesn't seem to like this, though: accessing <serverIP>:8080 just gets me a 404.  I've attached the logs, but the problem seems to be (from /var/log/fess/server_0.log):

> Mar 01, 2017 4:54:01 PM org.apache.catalina.core.StandardContext filterStart
> SEVERE: Exception starting filter lastaPrepareFilter
> org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
> /* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
> Failed to initialize the container.
> 
> [Path]
> esclient.xml
> 
> [Namespace]
> null
> 
> [Included by]
> esflute_config.xml
> esflute_user.xml
> esflute_log.xml
> * * * * * * * * * */
>         at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463)
<snip>
> Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.FessEsClient, because [fess.update] IndexNotFoundException[no such index]

I think I'm missing some of the config required for Fess and ES to talk to each other, but it's not clear from the install docs what I've done wrong.

[elasticsearch.log.txt](https://github.com/codelibs/fess/files/813300/elasticsearch.log.txt)
[fess.log.txt](https://github.com/codelibs/fess/files/813301/fess.log.txt)
[server_0.log.txt](https://github.com/codelibs/fess/files/813302/server_0.log.txt)

**Comment by marevol** [comment]
```
[2017-03-02T09:29:48,487][WARN ][o.e.a.i.TransportIndexAction] [jz0uh6P] unexpected error during the primary phase for action [indices:data/write/index], request [index {[.configsync][file][c3lub255bS50eHQ], source[{"path":"synonym.txt","content":"ZmVzcyzjg5XjgqfjgrkK","@timestamp":"2017-03-02T09:29:48.312Z"}]}]
org.elasticsearch.indices.IndexClosedException: closed
```

Elasticsearch does not seem to work correctly...

1. Stop Fess
2. Delete .configsync index: curl -XDELETE http://150.150.10.69:9200/.configsync
3. Restart Elasticsearch
4. Check if .configsync index exists
5. Start Fess

**Comment by IanRarity** [comment]
That worked; I now have a working admin interface on :8080, thanks!

If I try to log in at :8080/admin with the default admin/admin credentials, though, I get "Your request might have been processed before this request. Please check and retry it".

**Comment by robinComa** [comment]
Hello,

I have the same issue with the version 11.4.5
This is my issue : 
`
2018-01-02 16:06:11,291 [localhost-startStop-1] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:11,377 [localhost-startStop-1] ERROR Failed to initialize Lasta Di.
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
esclient.xml

[Namespace]
null

[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml
* * * * * * * * * */
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:66) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81) ~[lastaflute-1.0.0-RC6.jar:?]
        at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45) ~[lastaflute-1.0.0-RC6.jar:?]
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:136) [lastaflute-1.0.0-RC6.jar:?]
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94) [lastaflute-1.0.0-RC6.jar:?]
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285) [classes/:?]
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:266) [classes/:?]
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108) [classes/:?]
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4591) [classes/:?]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5233) [classes/:?]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [classes/:?]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [classes/:?]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [classes/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_77]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_77]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.FessEsClient, because NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300}]]
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
        ... 23 more
Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300}]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[elasticsearch-5.6.5.jar:5.6.5]
        at org.codelibs.fess.es.client.FessEsClient.waitForYellowStatus(FessEsClient.java:597) ~[classes/:?]
        at org.codelibs.fess.es.client.FessEsClient.open(FessEsClient.java:303) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
        at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434) ~[lasta-di-0.7.5.jar:?]
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413) ~[lasta-di-0.7.5.jar:?]
        ... 23 more
2018-01-02 16:06:16,021 [elasticsearch[_client_][generic][T#2]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:21,037 [elasticsearch[_client_][generic][T#1]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:26,053 [elasticsearch[_client_][generic][T#4]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:31,060 [elasticsearch[_client_][generic][T#2]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:36,067 [elasticsearch[_client_][generic][T#1]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:41,072 [elasticsearch[_client_][generic][T#3]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:46,076 [elasticsearch[_client_][generic][T#4]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:51,083 [elasticsearch[_client_][generic][T#1]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:06:56,088 [elasticsearch[_client_][generic][T#3]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:07:01,095 [elasticsearch[_client_][generic][T#4]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:07:06,100 [elasticsearch[_client_][generic][T#1]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:07:11,105 [elasticsearch[_client_][generic][T#3]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:07:16,110 [elasticsearch[_client_][generic][T#4]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:07:21,116 [elasticsearch[_client_][generic][T#1]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
2018-01-02 16:07:26,122 [elasticsearch[_client_][generic][T#3]] WARN  node {#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
`

Tanks by advance for your reply!

**Comment by marevol** [comment]
Your installation might be failed.
See [Installation Guilde](http://fess.codelibs.org/11.4/install/install.html).

**Comment by robinComa** [comment]
Hi Shinsuke, thanks for your reply.
J'ai lu cette page tout hier après midi :-)
All is already done.
Do you think it's the configuration of FESS or Elastic Search?
Because I am not the owner of the ELK, it is my OPS, so for me /var/lib/elasticsearch/ is /tech/elasticsearch/elastic/***

**Comment by marevol** [comment]
> Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{CIBwoSHFQ0-MuAFdqD_90w}{localhost}{127.0.0.1:9300}]

Elasticsearch is not available.

**Comment by robinComa** [comment]
`[root@xxxxx elasticsearch]# service elasticsearch status
Redirecting to /bin/systemctl status  elasticsearch.service
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/elasticsearch.service.d
           └─elasticsearch.conf
   Active: active (running) since Tue 2018-01-02 16:01:25 UTC; 21h ago
     Docs: http://www.elastic.co
  Process: 7064 ExecStartPre=/tech/elastic/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
Main PID: 7067 (java)
   CGroup: /xxx.xxx/elasticsearch.service
           └─7067 /xxx/xxx/xxx/xxx/xxx-Xms4g -Xmx4g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMS...
 
Jan 02 16:01:36 xxxx elasticsearch[7067]: [2018-01-02T16:01:36,051][INFO ][o.e.c.m.MetaDataCreateIndexService] [tlsdbkmnes...[file]
(…)
Hint: Some lines were ellipsized, use -l to show in full.`

Elastic is correctly configured : 
xxx/elasticsearch-5.5.2/config/elasticsearch.yml
`# Set a custom port for TCP (by default 9200-9300) :
#
transport.tcp.port: 9300`

And the port is already in use : 
![image](https://user-images.githubusercontent.com/2729768/34523233-dd68e504-f096-11e7-8fc4-c5e2cc506c35.png)

Any idea?

**Comment by robinComa** [comment]
Hum, when I change my configuration : 
![image](https://user-images.githubusercontent.com/2729768/34526249-367ff6ea-f0a2-11e7-9fbf-fe84f14f9939.png)

The logs are the same when I restart the services : 
![image](https://user-images.githubusercontent.com/2729768/34526269-4abe36a8-f0a2-11e7-8949-5cc91e247400.png)

The config is not take into account?

**Comment by robinComa** [comment]
Another thing is thant the cluster_uuid is not correct, my logs are : 
![image](https://user-images.githubusercontent.com/2729768/34527828-27413126-f0a7-11e7-83de-acc60b1dbafd.png)
But my cluster_uuid is : Eejp8hpIThSJiIjnOGKOrw
`
{
name: "tlsdbkmnes01",
cluster_name: "kamino-dev",
cluster_uuid: "Eejp8hpIThSJiIjnOGKOrw",
version: {
number: "5.5.2",
build_hash: "b2f0c09",
build_date: "2017-08-14T12:33:14.154Z",
build_snapshot: false,
lucene_version: "6.6.0"
},
tagline: "You Know, for Search"
}
`
Why does it take the wrong cluster_uuid?

**Comment by marevol** [comment]
If you changed a cluster name, you need to modify elasticsearch.cluster.name in fess_config.properties.

**Comment by robinComa** [comment]
Thanks @marevol that's works now!
I have a last question, because my production env expose a secure Elastic over SSL.
Is it possible to configure ssl on FESS?

**Comment by marevol** [comment]
We recommend to use a reverse proxy, such as using apache or nginx.

**Comment by robinComa** [comment]
Thanks for your reply @marevol , but we want an end to end security between FESS and elasticsearch.
Have you got a solution?

**Comment by robinComa** [comment]
Sorry it is not the good issue to speak about SSL, I add a comment here : 
[#1162](https://github.com/codelibs/fess/issues/1162)
